views:
  groupBits:
    ParLights: 1
    VintageLights: 2
    BarLights: 4
  custom:
    - name: Test
      bit: 8
      groups:
        - ParLights
        - BarLights
    - name: Test2
      bit: 16
      groups:
        - BarLights
