/*
 * Canonical Live Touch pixel-view reader.
 *
 * Geometry is generated by the simulation's pixel-map resolver and stored in
 * touch_control_pixel_views.json. This file deliberately contains no fixture
 * coordinates. It verifies both the authored YAML and the engine's live model
 * topology, then applies only a deterministic final viewport reprojection.
 */
(function installTouchPixelViews(root) {
  'use strict';

  if (!root.DeckPixelProjection || typeof root.DeckPixelProjection.layoutView !== 'function') {
    throw new Error('Deck pixel projection authority did not load');
  }

  var SCHEMA_VERSION = 4;
  var VIEW_AXES = {
    top_down: ['nx', 'nz'],
    front: ['nx', 'ny'],
    back: ['nx', 'ny'],
    strands: ['nx', 'nz'],
    te_sign: ['nz', 'ny'],
  };
  var MAX_DPR = 2;
  var MIN_VIEW_ZOOM = 0.5;
  var MAX_VIEW_ZOOM = 4;
  var VIEW_ZOOM_STEP = 1.25;
  var ARTIFACT_URL = 'touch_control_pixel_views.json';
  var VIEWS_SOURCE_URL = '/simulation/scenes/titanic_normalized/pixel_map_views.yaml';
  var CAMERAS_SOURCE_URL = '/simulation/scenes/titanic_normalized/cameras.yaml';
  var RESOLVER_SOURCE_URLS = [
    '/simulation/src/gui/pixel_map/pixel_map_layout.js',
    '/simulation/src/gui/pixel_map/pixel_map_views.js',
  ];
  var state = {
    artifact: null,
    view: null,
    canvas: null,
    pad: null,
    errorElement: null,
    staticVerified: false,
    engineVerified: false,
    screenGlyphs: [],
    resizeObserver: null,
    readyPromise: null,
    readyStatus: 'idle',
    previewPointers: new Map(),
    previewPixelIndices: new Set(),
    previewFrame: null,
    previewEvents: new Map(),
    drawFrame: null,
    panX: 0,
    panY: 0,
    zoom: 1,
    panMode: false,
    navigationPointers: new Map(),
    navigationGesture: null,
    viewSelect: null,
    panButton: null,
    zoomOutButton: null,
    zoomInButton: null,
    zoomValue: null,
    fitButton: null,
    layoutDirty: true,
    baseCanvas: null,
    glyphByPixel: new Map(),
    cachedPadRect: null,
    cachedCanvasRect: null,
    cachedWorldPerPx: null,
    staticRenderCount: 0,
    previewRenderCount: 0,
    reprojectCount: 0,
    canvasResizeCount: 0,
  };

  function requireFinite(value, label) {
    if (typeof value !== 'number' || !isFinite(value)) {
      throw new Error(label + ' must be finite');
    }
  }

  function clampZoom(value) {
    requireFinite(value, 'view zoom');
    return Math.min(MAX_VIEW_ZOOM, Math.max(MIN_VIEW_ZOOM, value));
  }

  /**
   * Change zoom without moving the point under the operator's fingers.
   * Pan is measured from the viewport centre, matching reprojectView().
   */
  function zoomAroundPoint(zoom, panX, panY, nextZoom, anchorX, anchorY, width, height) {
    [zoom, panX, panY, nextZoom, anchorX, anchorY, width, height].forEach(function (value) {
      requireFinite(value, 'zoom transform value');
    });
    if (zoom <= 0 || width <= 0 || height <= 0) {
      throw new Error('zoom transform needs positive zoom and viewport dimensions');
    }
    nextZoom = clampZoom(nextZoom);
    var ratio = nextZoom / zoom;
    var fromCenterX = anchorX - width / 2;
    var fromCenterY = anchorY - height / 2;
    return {
      zoom: nextZoom,
      panX: fromCenterX - (fromCenterX - panX) * ratio,
      panY: fromCenterY - (fromCenterY - panY) * ratio,
    };
  }

  function sha256(text) {
    // CaptainPad loads the simulation over the show LAN's plain HTTP origin.
    // WebCrypto `subtle` is unavailable on non-secure origins, so source
    // freshness uses this mandatory local SHA-256 implementation. It is not a
    // fallback: every runtime follows the same offline path.
    if (typeof root.TextEncoder !== 'function') {
      return Promise.reject(new Error('TextEncoder is unavailable; pixel views cannot be verified'));
    }
    var constants = [
      0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
      0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
      0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
      0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
      0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
      0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
      0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
      0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
      0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
      0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
      0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
      0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
      0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
      0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
      0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
      0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    ];
    var hash = [
      0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
      0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
    ];
    var bytes = new root.TextEncoder().encode(text);
    var paddedLength = Math.ceil((bytes.length + 9) / 64) * 64;
    var padded = new Uint8Array(paddedLength);
    padded.set(bytes);
    padded[bytes.length] = 0x80;
    var bitLength = bytes.length * 8;
    var dataView = new DataView(padded.buffer);
    dataView.setUint32(paddedLength - 8, Math.floor(bitLength / 0x100000000), false);
    dataView.setUint32(paddedLength - 4, bitLength >>> 0, false);
    var words = new Uint32Array(64);
    function rotateRight(value, amount) {
      return (value >>> amount) | (value << (32 - amount));
    }
    for (var offset = 0; offset < paddedLength; offset += 64) {
      for (var word = 0; word < 16; word++) {
        words[word] = dataView.getUint32(offset + word * 4, false);
      }
      for (word = 16; word < 64; word++) {
        var s0 = rotateRight(words[word - 15], 7) ^ rotateRight(words[word - 15], 18) ^
          (words[word - 15] >>> 3);
        var s1 = rotateRight(words[word - 2], 17) ^ rotateRight(words[word - 2], 19) ^
          (words[word - 2] >>> 10);
        words[word] = (words[word - 16] + s0 + words[word - 7] + s1) >>> 0;
      }
      var a = hash[0], b = hash[1], c = hash[2], d = hash[3];
      var e = hash[4], f = hash[5], g = hash[6], h = hash[7];
      for (word = 0; word < 64; word++) {
        var upper = rotateRight(e, 6) ^ rotateRight(e, 11) ^ rotateRight(e, 25);
        var choose = (e & f) ^ (~e & g);
        var temp1 = (h + upper + choose + constants[word] + words[word]) >>> 0;
        var lower = rotateRight(a, 2) ^ rotateRight(a, 13) ^ rotateRight(a, 22);
        var majority = (a & b) ^ (a & c) ^ (b & c);
        var temp2 = (lower + majority) >>> 0;
        h = g; g = f; f = e; e = (d + temp1) >>> 0;
        d = c; c = b; b = a; a = (temp1 + temp2) >>> 0;
      }
      hash[0] = (hash[0] + a) >>> 0;
      hash[1] = (hash[1] + b) >>> 0;
      hash[2] = (hash[2] + c) >>> 0;
      hash[3] = (hash[3] + d) >>> 0;
      hash[4] = (hash[4] + e) >>> 0;
      hash[5] = (hash[5] + f) >>> 0;
      hash[6] = (hash[6] + g) >>> 0;
      hash[7] = (hash[7] + h) >>> 0;
    }
    return Promise.resolve(hash.map(function (value) {
      return value.toString(16).padStart(8, '0');
    }).join(''));
  }

  function canonicalSource(text) {
    return text.replace(/\r\n?/g, '\n');
  }

  function topologyPayload(pixels) {
    if (!Array.isArray(pixels) || !pixels.length) {
      throw new Error('engine pixel layout is empty');
    }
    return pixels.map(function (pixel, index) {
      if (!pixel || pixel.i !== index) {
        throw new Error('engine pixel identity/order mismatch at ' + index);
      }
      ['x', 'y', 'z', 'nx', 'ny', 'nz'].forEach(function (field) {
        requireFinite(pixel[field], 'engine pixel ' + index + '.' + field);
      });
      if (!Number.isInteger(pixel.localIndex) || pixel.localIndex < 0) {
        throw new Error('engine pixel ' + index + '.localIndex is invalid');
      }
      return [
        pixel.i,
        pixel.x,
        pixel.y,
        pixel.z,
        pixel.nx,
        pixel.ny,
        pixel.nz,
        pixel.group == null ? null : pixel.group,
        pixel.type == null ? null : pixel.type,
        pixel.fixtureType == null ? null : pixel.fixtureType,
        pixel.fId == null ? null : pixel.fId,
        pixel.sId == null ? null : pixel.sId,
        pixel.localIndex,
      ];
    });
  }

  function topologyFingerprint(pixels) {
    return sha256(JSON.stringify(topologyPayload(pixels)));
  }

  function validateArtifact(artifact) {
    if (!artifact || artifact.schemaVersion !== SCHEMA_VERSION) {
      throw new Error('unsupported or missing pixel-view artifact schema');
    }
    if (!artifact.source || artifact.source.scene !== 'titanic_normalized') {
      throw new Error('pixel-view artifact is not for the Titanic scene');
    }
    ['modelFingerprint', 'modelSourceFingerprint', 'viewsFingerprint', 'camerasFingerprint', 'resolverFingerprint',
      'resolvedFingerprint']
      .forEach(function (field) {
        if (!/^[0-9a-f]{64}$/.test(artifact.source[field] || '')) {
          throw new Error('pixel-view artifact has invalid ' + field);
        }
      });
    if (!Number.isInteger(artifact.modelPixelCount) || artifact.modelPixelCount <= 0) {
      throw new Error('pixel-view artifact has an invalid model pixel count');
    }
    if (!artifact.design) throw new Error('pixel-view artifact has no design space');
    requireFinite(artifact.design.width, 'artifact design.width');
    requireFinite(artifact.design.height, 'artifact design.height');
    requireFinite(artifact.design.panelGap, 'artifact design.panelGap');
    if (artifact.design.width <= 0 || artifact.design.height <= 0) {
      throw new Error('pixel-view design space must be positive');
    }
    if (!Array.isArray(artifact.views) || !artifact.views.length) {
      throw new Error('pixel-view artifact has no views');
    }
    artifact.views.forEach(function (view) {
      if (!view || typeof view.id !== 'string' || !Array.isArray(view.panels) || !view.panels.length) {
        throw new Error('pixel-view artifact contains an invalid view');
      }
      if (!view.framing) throw new Error("view '" + view.id + "' has no framing");
      if (!Number.isInteger(view.pixelCount) || view.pixelCount <= 0) {
        throw new Error("view '" + view.id + "' has an invalid pixel count");
      }
      if (!Number.isInteger(view.paintPixelCount) || view.paintPixelCount < view.pixelCount ||
          !Array.isArray(view.paintPixelIndices) ||
          view.paintPixelIndices.length !== view.paintPixelCount) {
        throw new Error("view '" + view.id + "' has an invalid paint mask");
      }
      var expectedAxes = VIEW_AXES[view.id];
      if (!expectedAxes || view.axisX !== expectedAxes[0] || view.axisY !== expectedAxes[1]) {
        throw new Error("view '" + view.id + "' has no supported canonical axis pair");
      }
      ['zoom', 'panX', 'panY'].forEach(function (field) {
        requireFinite(view.framing[field], "view '" + view.id + "'.framing." + field);
      });
      var identities = new Set();
      var glyphCount = 0;
      view.panels.forEach(function (panel) {
        if (!panel || typeof panel.id !== 'string' || !Array.isArray(panel.glyphs) ||
            !panel.glyphs.length) {
          throw new Error("view '" + view.id + "' contains an invalid panel");
        }
        requireFinite(panel.weight, "view '" + view.id + "' panel weight");
        panel.glyphs.forEach(function (glyph) {
          if (!Number.isInteger(glyph.pixelIndex) || glyph.pixelIndex < 0 ||
              glyph.pixelIndex >= artifact.modelPixelCount) {
            throw new Error("view '" + view.id + "' has an invalid pixel identity");
          }
          if (identities.has(glyph.pixelIndex)) {
            throw new Error("view '" + view.id + "' renders pixel " + glyph.pixelIndex + ' twice');
          }
          identities.add(glyph.pixelIndex);
          ['x', 'y', 'sizeX', 'sizeY', 'rotation'].forEach(function (field) {
            requireFinite(glyph[field], "view '" + view.id + "' glyph." + field);
          });
          if (glyph.shape !== 'circle' && glyph.shape !== 'square') {
            throw new Error("view '" + view.id + "' glyph has an invalid shape");
          }
          if (glyph.effect !== null && glyph.effect !== 'upwash') {
            throw new Error("view '" + view.id + "' glyph has an invalid effect");
          }
          if (!glyph.world) throw new Error("view '" + view.id + "' glyph has no world identity");
          ['nx', 'ny', 'nz'].forEach(function (field) {
            requireFinite(glyph.world[field], "view '" + view.id + "' glyph.world." + field);
          });
          glyphCount++;
        });
      });
      if (glyphCount !== view.pixelCount) {
        throw new Error("view '" + view.id + "' pixel count does not match its glyphs");
      }
      var paintIdentities = new Set();
      view.paintPixelIndices.forEach(function (pixelIndex) {
        if (!Number.isInteger(pixelIndex) || pixelIndex < 0 ||
            pixelIndex >= artifact.modelPixelCount || paintIdentities.has(pixelIndex)) {
          throw new Error("view '" + view.id + "' has an invalid paint identity");
        }
        paintIdentities.add(pixelIndex);
      });
      identities.forEach(function (pixelIndex) {
        if (!paintIdentities.has(pixelIndex)) {
          throw new Error("view '" + view.id + "' paint mask omits visible pixel " + pixelIndex);
        }
      });
    });
    return artifact;
  }

  function verifyResolvedFingerprint(artifact) {
    return sha256(JSON.stringify({
      modelPixelCount: artifact.modelPixelCount,
      design: artifact.design,
      views: artifact.views,
    })).then(function (fingerprint) {
      if (fingerprint !== artifact.source.resolvedFingerprint) {
        throw new Error('pixel-view resolved geometry fingerprint does not match its artifact');
      }
      return artifact;
    });
  }

  function flattenProjectionView(view) {
    var panels = [];
    var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    view.panels.forEach(function (panel) {
      var panelMinX = Infinity, panelMinY = Infinity, panelMaxX = -Infinity, panelMaxY = -Infinity;
      panel.glyphs.forEach(function (glyph) {
        var halfX = glyph.sizeX / 2;
        var halfY = glyph.sizeY / 2;
        panelMinX = Math.min(panelMinX, glyph.x - halfX);
        panelMaxX = Math.max(panelMaxX, glyph.x + halfX);
        panelMinY = Math.min(panelMinY, glyph.y - halfY);
        panelMaxY = Math.max(panelMaxY, glyph.y + halfY);
      });
      var bounds = { minX: panelMinX, minY: panelMinY, maxX: panelMaxX, maxY: panelMaxY };
      panels.push({ id: panel.id, weight: panel.weight, bounds: bounds });
      minX = Math.min(minX, panelMinX);
      maxX = Math.max(maxX, panelMaxX);
      minY = Math.min(minY, panelMinY);
      maxY = Math.max(maxY, panelMaxY);
    });
    return { panels: panels, bounds: { minX: minX, minY: minY, maxX: maxX, maxY: maxY } };
  }

  /**
   * Reproject resolved design coordinates into a final viewport. Pixel identity
   * and world coordinates are carried unchanged, so resize is display-only.
   */
  function reprojectView(view, design, width, height, panX, panY, zoom) {
    requireFinite(width, 'viewport width');
    requireFinite(height, 'viewport height');
    if (width <= 0 || height <= 0) throw new Error('viewport must be positive');
    var transforms = root.DeckPixelProjection.layoutView(
      flattenProjectionView(view), design, width, height);
    var out = [];
    view.panels.forEach(function (panel, index) {
      var transform = transforms[index];
      panel.glyphs.forEach(function (glyph) {
        out.push({
          pixelIndex: glyph.pixelIndex,
          panelId: panel.id,
          fixtureKey: glyph.fixtureKey,
          fixtureType: glyph.fixtureType,
          kind: glyph.kind,
          group: glyph.group,
          x: glyph.x * transform.scale + transform.offsetX,
          y: glyph.y * transform.scale + transform.offsetY,
          sizeX: glyph.sizeX * transform.scale,
          sizeY: glyph.sizeY * transform.scale,
          shape: glyph.shape,
          effect: glyph.effect,
          rotation: glyph.rotation,
          world: glyph.world,
        });
      });
    });
    if (!out.length) throw new Error("view '" + view.id + "' has no glyphs to fit");
    var viewZoom = clampZoom(zoom == null ? 1 : zoom);
    if (viewZoom !== 1 || panX || panY) {
      out.forEach(function (glyph) {
        glyph.x = (glyph.x - width / 2) * viewZoom + width / 2 + (panX || 0);
        glyph.y = (glyph.y - height / 2) * viewZoom + height / 2 + (panY || 0);
        glyph.sizeX *= viewZoom;
        glyph.sizeY *= viewZoom;
      });
    }
    return out;
  }

  function failClosed(message) {
    var full = 'PIXEL VIEW UNAVAILABLE — ' + message;
    state.staticVerified = false;
    state.engineVerified = false;
    if (state.errorElement) {
      state.errorElement.hidden = false;
      state.errorElement.textContent = full;
    }
    if (state.pad) {
      state.pad.classList.add('pixel-view-failed');
      state.pad.setAttribute('aria-disabled', 'true');
    }
    if (state.canvas) {
      var context = state.canvas.getContext('2d');
      context.setTransform(1, 0, 0, 1, 0, 0);
      context.clearRect(0, 0, state.canvas.width, state.canvas.height);
    }
    console.error('[touch-pixel-views] ' + full);
  }

  function markPending() {
    state.staticVerified = false;
    state.engineVerified = false;
    if (state.errorElement) {
      state.errorElement.hidden = true;
      state.errorElement.textContent = '';
    }
    if (state.pad) {
      state.pad.classList.add('pixel-view-failed');
      state.pad.setAttribute('aria-disabled', 'true');
    }
    if (state.canvas) {
      var context = state.canvas.getContext('2d');
      context.setTransform(1, 0, 0, 1, 0, 0);
      context.clearRect(0, 0, state.canvas.width, state.canvas.height);
    }
  }

  function failEngine(message) {
    var full = 'PIXEL VIEW UNAVAILABLE — ' + message;
    state.engineVerified = false;
    if (state.errorElement) {
      state.errorElement.hidden = false;
      state.errorElement.textContent = full;
    }
    if (state.pad) {
      state.pad.classList.add('pixel-view-failed');
      state.pad.setAttribute('aria-disabled', 'true');
    }
    console.error('[touch-pixel-views] ' + full);
  }

  function showVerified() {
    if (state.errorElement) {
      state.errorElement.hidden = true;
      state.errorElement.textContent = '';
    }
    if (state.pad) {
      state.pad.classList.remove('pixel-view-failed');
      state.pad.removeAttribute('aria-disabled');
    }
  }

  function groupColour(group) {
    var hash = 2166136261;
    for (var index = 0; index < group.length; index++) {
      hash ^= group.charCodeAt(index);
      hash = Math.imul(hash, 16777619);
    }
    var hue = (hash >>> 0) % 360;
    var lightness = ((hash >>> 8) & 1) ? 72 : 56;
    return 'hsl(' + hue + ' 95% ' + lightness + '%)';
  }

  function traceGlyph(context, glyph) {
    var halfX = Math.max(1.8, glyph.sizeX / 2);
    var halfY = Math.max(1.8, glyph.sizeY / 2);
    var radians = glyph.rotation * Math.PI / 180;
    context.beginPath();
    if (glyph.shape === 'circle') {
      context.ellipse(glyph.x, glyph.y, halfX, halfY, radians, 0, Math.PI * 2);
    } else {
      context.save();
      context.translate(glyph.x, glyph.y);
      context.rotate(radians);
      context.rect(-halfX, -halfY, halfX * 2, halfY * 2);
      context.restore();
    }
  }

  function glyphExtents(glyph) {
    var halfX = Math.max(1.8, glyph.sizeX / 2);
    var halfY = Math.max(1.8, glyph.sizeY / 2);
    var radians = glyph.rotation * Math.PI / 180;
    var cosine = Math.abs(Math.cos(radians));
    var sine = Math.abs(Math.sin(radians));
    return {
      x: cosine * halfX + sine * halfY,
      y: sine * halfX + cosine * halfY,
    };
  }

  function drawGlyph(context, glyph) {
    traceGlyph(context, glyph);
    context.fillStyle = groupColour(glyph.group || 'ungrouped');
    context.fill();
    context.stroke();
  }

  function invalidateLayout() {
    state.layoutDirty = true;
    state.cachedPadRect = null;
    state.cachedCanvasRect = null;
    state.cachedWorldPerPx = null;
  }

  function scheduleDraw(layoutChanged) {
    if (layoutChanged) invalidateLayout();
    if (state.drawFrame !== null) return;
    state.drawFrame = root.requestAnimationFrame(function () {
      state.drawFrame = null;
      draw();
    });
  }

  function rebuildBase(width, height, dpr) {
    state.reprojectCount++;
    state.screenGlyphs = reprojectView(
      state.view, state.artifact.design, width, height, state.panX, state.panY, state.zoom);
    state.glyphByPixel.clear();
    state.screenGlyphs.forEach(function (glyph) { state.glyphByPixel.set(glyph.pixelIndex, glyph); });
    if (!state.baseCanvas) state.baseCanvas = root.document.createElement('canvas');
    state.baseCanvas.width = Math.round(width * dpr);
    state.baseCanvas.height = Math.round(height * dpr);
    var base = state.baseCanvas.getContext('2d');
    base.setTransform(dpr, 0, 0, dpr, 0, 0);
    base.clearRect(0, 0, width, height);
    base.lineWidth = 1;
    base.strokeStyle = 'rgba(3,8,18,.92)';
    state.screenGlyphs.forEach(function (glyph) { drawGlyph(base, glyph); });
    state.staticRenderCount++;
    state.layoutDirty = false;
  }

  function draw() {
    if (!state.staticVerified || !state.canvas || !state.view) return;
    var width = state.canvas.clientWidth;
    var height = state.canvas.clientHeight;
    if (!width || !height) return;
    var dpr = Math.min(MAX_DPR, root.devicePixelRatio || 1);
    var pixelWidth = Math.round(width * dpr);
    var pixelHeight = Math.round(height * dpr);
    if (state.canvas.width !== pixelWidth || state.canvas.height !== pixelHeight) {
      state.canvas.width = pixelWidth;
      state.canvas.height = pixelHeight;
      state.canvasResizeCount++;
      state.layoutDirty = true;
    }
    if (state.layoutDirty) rebuildBase(width, height, dpr);
    var context = state.canvas.getContext('2d');
    context.setTransform(1, 0, 0, 1, 0, 0);
    context.clearRect(0, 0, state.canvas.width, state.canvas.height);
    context.drawImage(state.baseCanvas, 0, 0);
    if (state.previewPixelIndices.size) {
      state.previewRenderCount++;
      context.setTransform(dpr, 0, 0, dpr, 0, 0);
      context.lineWidth = 3;
      context.strokeStyle = 'rgba(255,255,255,.98)';
      state.previewPixelIndices.forEach(function (pixelIndex) {
        var glyph = state.glyphByPixel.get(pixelIndex);
        if (!glyph) return;
        traceGlyph(context, glyph);
        context.stroke();
      });
    }
  }

  /** Exact world-space ellipse/segment test used by spatial_paint.js. */
  function affectedPixelIndices(glyphs, options) {
    if (!options) throw new Error('brush preview options are required');
    var axisX = options.axisX;
    var axisY = options.axisY;
    if (!Object.keys(VIEW_AXES).some(function (id) {
      return VIEW_AXES[id][0] === axisX && VIEW_AXES[id][1] === axisY;
    })) {
      throw new Error('brush preview has an unsupported axis pair');
    }
    ['targetX', 'targetY', 'radius', 'radiusY'].forEach(function (field) {
      requireFinite(options[field], 'brush preview.' + field);
    });
    if (options.radius <= 0 || options.radiusY <= 0) {
      throw new Error('brush radius must be positive');
    }
    var ax = options.prevX == null ? options.targetX : options.prevX;
    var ay = options.prevY == null ? options.targetY : options.prevY;
    var sx = (options.targetX - ax) / options.radius;
    var sy = (options.targetY - ay) / options.radiusY;
    var segmentLength2 = sx * sx + sy * sy;
    var selected = new Set();
    // A stroke lives in ONE panel. Panels of a view can share world-axis
    // ranges (the normalized model z-aligns both TE signs onto one nz/ny
    // band), so an unscoped world ellipse would spill into the sibling
    // panel's surface; the tapped panel bounds the selection.
    var panelScope = options.panelId == null ? null : options.panelId;
    glyphs.forEach(function (glyph) {
      if (panelScope !== null && glyph.panelId !== panelScope) return;
      var dx = (glyph.world[axisX] - ax) / options.radius;
      var dy = (glyph.world[axisY] - ay) / options.radiusY;
      if (segmentLength2 > 0) {
        var along = (dx * sx + dy * sy) / segmentLength2;
        along = Math.min(Math.max(along, 0), 1);
        dx -= sx * along;
        dy -= sy * along;
      }
      if (dx * dx + dy * dy < 1) selected.add(glyph.pixelIndex);
    });
    return selected;
  }

  function nearestScreenGlyphIn(glyphs, x, y) {
    var best = null;
    var bestDistance = Infinity;
    glyphs.forEach(function (glyph) {
      var dx = x - glyph.x;
      var dy = y - glyph.y;
      var distance = dx * dx + dy * dy;
      if (distance < bestDistance ||
          (distance === bestDistance && glyph.pixelIndex < best.pixelIndex)) {
        best = glyph;
        bestDistance = distance;
      }
    });
    return best;
  }

  function nearestScreenGlyph(x, y) {
    if (!state.staticVerified || !state.screenGlyphs.length) return null;
    return nearestScreenGlyphIn(state.screenGlyphs, x, y);
  }

  function screenPointToTarget(glyphs, view, x, y) {
    if (!view || !VIEW_AXES[view.id] || view.axisX !== VIEW_AXES[view.id][0] ||
        view.axisY !== VIEW_AXES[view.id][1]) {
      throw new Error('screen mapping needs a supported canonical view');
    }
    var glyph = nearestScreenGlyphIn(glyphs, x, y);
    if (!glyph) throw new Error('pixel view contains no addressable glyphs');
    return {
      pixelIndex: glyph.pixelIndex,
      panelId: glyph.panelId,
      axisX: view.axisX,
      axisY: view.axisY,
      targetX: glyph.world[view.axisX],
      targetY: glyph.world[view.axisY],
      nx: glyph.world.nx,
      ny: glyph.world.ny,
      nz: glyph.world.nz,
    };
  }

  function nearestWorldGlyph(targetX, targetY) {
    if (!state.staticVerified || !state.screenGlyphs.length) return null;
    var best = null;
    var bestDistance = Infinity;
    state.screenGlyphs.forEach(function (glyph) {
      var dx = targetX - glyph.world[state.view.axisX];
      var dy = targetY - glyph.world[state.view.axisY];
      var distance = dx * dx + dy * dy;
      if (distance < bestDistance ||
          (distance === bestDistance && glyph.pixelIndex < best.pixelIndex)) {
        best = glyph;
        bestDistance = distance;
      }
    });
    return best;
  }

  function padPxToWorld(x, y, width, height) {
    if (!state.staticVerified) throw new Error('pixel view is not verified');
    requireFinite(width, 'pad width');
    requireFinite(height, 'pad height');
    var canvasWidth = state.canvas.clientWidth || width;
    var canvasHeight = state.canvas.clientHeight || height;
    return screenPointToTarget(state.screenGlyphs, state.view,
      x * canvasWidth / width, y * canvasHeight / height);
  }

  function padToWorld(u, v) {
    if (!state.pad) throw new Error('pixel view is not mounted');
    var rect = state.cachedPadRect || state.pad.getBoundingClientRect();
    var canvasRect = state.cachedCanvasRect || state.canvas.getBoundingClientRect();
    state.cachedPadRect = rect;
    state.cachedCanvasRect = canvasRect;
    return padPxToWorld(
      Math.min(Math.max(u, 0), 1) * rect.width - (canvasRect.left - rect.left),
      Math.min(Math.max(v, 0), 1) * rect.height - (canvasRect.top - rect.top),
      canvasRect.width,
      canvasRect.height,
    );
  }

  function worldToPad(targetX, targetY, width, height) {
    if (!state.staticVerified) throw new Error('pixel view is not verified');
    var glyph = nearestWorldGlyph(targetX, targetY);
    if (!glyph) throw new Error('pixel view contains no addressable glyphs');
    var canvasWidth = state.canvas.clientWidth || width;
    var canvasHeight = state.canvas.clientHeight || height;
    return {
      x: glyph.x * width / canvasWidth,
      y: glyph.y * height / canvasHeight,
      pixelIndex: glyph.pixelIndex,
    };
  }

  function worldPerPxForGlyphs(sourceGlyphs, view, target) {
    if (!Array.isArray(sourceGlyphs) || !sourceGlyphs.length) {
      throw new Error('pixel view has no glyph projection');
    }
    var targetGlyph = target && Number.isInteger(target.pixelIndex)
      ? sourceGlyphs.find(function (glyph) { return glyph.pixelIndex === target.pixelIndex; })
      : null;
    var glyphs = targetGlyph
      ? sourceGlyphs.filter(function (glyph) { return glyph.panelId === targetGlyph.panelId; })
      : sourceGlyphs;
    var minAxisX = Infinity, maxAxisX = -Infinity, minAxisY = Infinity, maxAxisY = -Infinity;
    glyphs.forEach(function (glyph) {
      minAxisX = Math.min(minAxisX, glyph.world[view.axisX]);
      maxAxisX = Math.max(maxAxisX, glyph.world[view.axisX]);
      minAxisY = Math.min(minAxisY, glyph.world[view.axisY]);
      maxAxisY = Math.max(maxAxisY, glyph.world[view.axisY]);
    });
    var minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    glyphs.forEach(function (glyph) {
      minX = Math.min(minX, glyph.x);
      maxX = Math.max(maxX, glyph.x);
      minY = Math.min(minY, glyph.y);
      maxY = Math.max(maxY, glyph.y);
    });
    return {
      x: (maxAxisX - minAxisX) / Math.max(1, maxX - minX),
      y: (maxAxisY - minAxisY) / Math.max(1, maxY - minY),
    };
  }

  function clearBrushPreview() {
    if (state.previewFrame !== null) {
      root.cancelAnimationFrame(state.previewFrame);
      state.previewFrame = null;
    }
    state.previewPointers.clear();
    state.previewEvents.clear();
    state.previewPixelIndices.clear();
    scheduleDraw(false);
  }

  function padWorldPerPx(width, height, target) {
    if (!state.staticVerified) throw new Error('pixel view is not verified');
    if (!state.screenGlyphs.length) {
      throw new Error('pixel view has no rendered display projection');
    }
    var targetGlyph = target && Number.isInteger(target.pixelIndex)
      ? state.glyphByPixel.get(target.pixelIndex) : null;
    if (!targetGlyph && state.cachedWorldPerPx) return state.cachedWorldPerPx;
    var result = worldPerPxForGlyphs(state.screenGlyphs, state.view, target);
    if (!targetGlyph) state.cachedWorldPerPx = result;
    return result;
  }

  function worldBrushRadii(fraction, target) {
    if (!state.staticVerified) {
      throw new Error('pixel-view source artifact is not verified');
    }
    if (!state.engineVerified) {
      throw new Error('pixel-view engine topology is not verified');
    }
    requireFinite(fraction, 'brush fraction');
    if (fraction <= 0) throw new Error('brush fraction must be positive');
    var design = state.artifact.design;
    var glyphs = reprojectView(state.view, design, design.width, design.height, 0, 0, 1);
    var per = worldPerPxForGlyphs(glyphs, state.view, target);
    var radiusPixels = fraction * design.width;
    return {
      x: Math.max(0.01, Math.min(1, radiusPixels * per.x)),
      y: Math.max(0.01, Math.min(2, radiusPixels * per.y)),
    };
  }

  function verifyEngineLayout(layout) {
    var REGEN_HINT = ' — verify the active Titanic model, then run: '
      + 'cd simulation && npm run pixel-views:export';
    var actualModel = layout && (layout.model || layout.scene) || 'unknown';
    var actualCount = layout && Number.isInteger(layout.returnedCount)
      ? layout.returnedCount
      : (layout && Array.isArray(layout.pixels) ? layout.pixels.length : 'unknown');
    var expectedCount = state.artifact ? state.artifact.modelPixelCount : 'unknown';
    if (!state.staticVerified || !state.artifact) {
      return Promise.reject(new Error('pixel-view artifact has not passed source verification'));
    }
    if (!layout || layout.scene !== 'titanic_normalized' || layout.model !== 'titanic_normalized') {
      var error = new Error("engine model is '" + actualModel + "' (" + actualCount
        + " pixels), expected 'titanic_normalized' (" + expectedCount + ' pixels)' + REGEN_HINT);
      failEngine(error.message);
      return Promise.reject(error);
    }
    if (layout.pixelCount !== state.artifact.modelPixelCount ||
        layout.returnedCount !== state.artifact.modelPixelCount ||
        !Array.isArray(layout.pixels) || layout.pixels.length !== state.artifact.modelPixelCount) {
      var countError = new Error("engine model '" + actualModel + "' pixel layout is incomplete: expected " +
        expectedCount + ', got ' + actualCount + REGEN_HINT);
      failEngine(countError.message);
      return Promise.reject(countError);
    }
    return topologyFingerprint(layout.pixels).then(function (fingerprint) {
      if (fingerprint !== state.artifact.source.modelFingerprint) {
        throw new Error("engine model '" + actualModel + "' (" + actualCount
          + ' pixels) topology does not match the generated Titanic view ('
          + expectedCount + ' pixels)' + REGEN_HINT);
      }
      state.artifact.views.forEach(function (view) {
        view.panels.forEach(function (panel) {
          panel.glyphs.forEach(function (glyph) {
            var live = layout.pixels[glyph.pixelIndex];
            if (!live || live.nx !== glyph.world.nx || live.ny !== glyph.world.ny ||
                live.nz !== glyph.world.nz) {
              throw new Error('resolved glyph ' + glyph.pixelIndex +
                ' does not preserve its engine world identity');
            }
          });
        });
      });
      state.engineVerified = true;
      showVerified();
      scheduleDraw(true);
      dispatchViewChange();
      return true;
    }).catch(function (error) {
      failEngine(error.message);
      throw error;
    });
  }

  function currentViewSpec() {
    if (!state.view) throw new Error('pixel view is not selected');
    return {
      viewId: state.view.id,
      axisX: state.view.axisX,
      axisY: state.view.axisY,
      pixelIndices: state.view.paintPixelIndices.slice(),
    };
  }

  function dispatchViewChange() {
    if (!state.engineVerified || typeof root.CustomEvent !== 'function') return;
    state.pad.dispatchEvent(new root.CustomEvent('touchpixelviewchange', {
      bubbles: true,
      detail: currentViewSpec(),
    }));
  }

  function selectView(viewId, notify) {
    if (!state.artifact) throw new Error('pixel-view artifact is not loaded');
    var view = state.artifact.views.find(function (candidate) { return candidate.id === viewId; });
    if (!view) throw new Error("pixel-view artifact has no '" + viewId + "' view");
    state.view = view;
    state.panX = 0;
    state.panY = 0;
    state.zoom = 1;
    clearBrushPreview();
    if (state.viewSelect) state.viewSelect.value = view.id;
    updateZoomReadout();
    scheduleDraw(true);
    if (notify !== false) dispatchViewChange();
    return currentViewSpec();
  }

  function installViewControls() {
    if (state.viewSelect) {
      state.viewSelect.textContent = '';
      state.artifact.views.forEach(function (view) {
        var option = root.document.createElement('option');
        option.value = view.id;
        option.textContent = view.label;
        state.viewSelect.appendChild(option);
      });
      state.viewSelect.value = state.view.id;
      state.viewSelect.addEventListener('change', function () {
        try { selectView(state.viewSelect.value, true); }
        catch (error) { failEngine(error.message); }
      });
    }
    if (state.panButton) {
      state.panButton.addEventListener('click', function () {
        if (state.navigationPointers.size || state.previewPointers.size) return;
        state.panMode = !state.panMode;
        state.panButton.classList.toggle('on', state.panMode);
        state.panButton.setAttribute('aria-pressed', state.panMode ? 'true' : 'false');
        state.panButton.textContent = state.panMode ? 'PAN ON' : 'PAN';
      });
    }
    if (state.zoomOutButton) {
      state.zoomOutButton.addEventListener('click', function () {
        if (state.navigationPointers.size || state.previewPointers.size) return;
        setZoomAt(state.zoom / VIEW_ZOOM_STEP);
      });
    }
    if (state.zoomInButton) {
      state.zoomInButton.addEventListener('click', function () {
        if (state.navigationPointers.size || state.previewPointers.size) return;
        setZoomAt(state.zoom * VIEW_ZOOM_STEP);
      });
    }
    if (state.fitButton) {
      state.fitButton.addEventListener('click', function () {
        if (state.navigationPointers.size || state.previewPointers.size) return;
        state.panX = 0;
        state.panY = 0;
        state.zoom = 1;
        updateZoomReadout();
        scheduleDraw(true);
      });
    }
  }

  function updateZoomReadout() {
    if (state.zoomValue) state.zoomValue.textContent = Math.round(state.zoom * 100) + '%';
    if (state.zoomOutButton) state.zoomOutButton.disabled = state.zoom <= MIN_VIEW_ZOOM;
    if (state.zoomInButton) state.zoomInButton.disabled = state.zoom >= MAX_VIEW_ZOOM;
  }

  function setZoomAt(nextZoom, anchorX, anchorY) {
    var rect = state.pad.getBoundingClientRect();
    var localX = anchorX == null ? rect.width / 2 : anchorX;
    var localY = anchorY == null ? rect.height / 2 : anchorY;
    var transformed = zoomAroundPoint(
      state.zoom, state.panX, state.panY, nextZoom,
      localX, localY, rect.width, rect.height);
    state.zoom = transformed.zoom;
    state.panX = transformed.panX;
    state.panY = transformed.panY;
    updateZoomReadout();
    scheduleDraw(true);
  }

  function installViewGesture() {
    function localPoint(event) {
      var rect = state.pad.getBoundingClientRect();
      return { x: event.clientX - rect.left, y: event.clientY - rect.top };
    }
    function beginGesture() {
      var entries = Array.from(state.navigationPointers.entries());
      if (!entries.length) {
        state.navigationGesture = null;
        return;
      }
      if (entries.length === 1) {
        state.navigationGesture = {
          kind: 'pan',
          pointerId: entries[0][0],
          start: entries[0][1],
          panX: state.panX,
          panY: state.panY,
        };
        return;
      }
      var first = entries[0][1];
      var second = entries[1][1];
      state.navigationGesture = {
        kind: 'pinch',
        pointerIds: [entries[0][0], entries[1][0]],
        startMidX: (first.x + second.x) / 2,
        startMidY: (first.y + second.y) / 2,
        startDistance: Math.max(1, Math.hypot(second.x - first.x, second.y - first.y)),
        zoom: state.zoom,
        panX: state.panX,
        panY: state.panY,
      };
    }
    function moveGesture() {
      var gesture = state.navigationGesture;
      if (!gesture) return;
      if (gesture.kind === 'pan') {
        var point = state.navigationPointers.get(gesture.pointerId);
        if (!point) return;
        state.panX = gesture.panX + point.x - gesture.start.x;
        state.panY = gesture.panY + point.y - gesture.start.y;
        scheduleDraw(true);
        return;
      }
      var first = state.navigationPointers.get(gesture.pointerIds[0]);
      var second = state.navigationPointers.get(gesture.pointerIds[1]);
      if (!first || !second) return;
      var midX = (first.x + second.x) / 2;
      var midY = (first.y + second.y) / 2;
      var distance = Math.max(1, Math.hypot(second.x - first.x, second.y - first.y));
      var rect = state.pad.getBoundingClientRect();
      var transformed = zoomAroundPoint(
        gesture.zoom, gesture.panX, gesture.panY,
        gesture.zoom * distance / gesture.startDistance,
        gesture.startMidX, gesture.startMidY, rect.width, rect.height);
      state.zoom = transformed.zoom;
      state.panX = transformed.panX + midX - gesture.startMidX;
      state.panY = transformed.panY + midY - gesture.startMidY;
      updateZoomReadout();
      scheduleDraw(true);
    }
    function capture(event) {
      if (!state.panMode || !state.engineVerified) return;
      event.preventDefault();
      event.stopImmediatePropagation();
      if (event.type === 'pointerdown') {
        if (state.navigationPointers.size >= 2 &&
            !state.navigationPointers.has(event.pointerId)) return;
        state.navigationPointers.set(event.pointerId, localPoint(event));
        try { state.pad.setPointerCapture(event.pointerId); } catch (error) {
          state.navigationPointers.delete(event.pointerId);
          beginGesture();
          return;
        }
        beginGesture();
        return;
      }
      if (event.type === 'pointermove' && state.navigationPointers.has(event.pointerId)) {
        state.navigationPointers.set(event.pointerId, localPoint(event));
        moveGesture();
        return;
      }
      if ((event.type === 'pointerup' || event.type === 'pointercancel') &&
          state.navigationPointers.has(event.pointerId)) {
        state.navigationPointers.delete(event.pointerId);
        beginGesture();
      }
    }
    ['pointerdown', 'pointermove', 'pointerup', 'pointercancel'].forEach(function (type) {
      state.pad.addEventListener(type, capture, true);
    });
    state.pad.addEventListener('wheel', function (event) {
      if (!state.panMode || !state.engineVerified) return;
      event.preventDefault();
      event.stopImmediatePropagation();
      var point = localPoint(event);
      setZoomAt(state.zoom * Math.exp(-event.deltaY * 0.002), point.x, point.y);
    }, { capture: true, passive: false });
  }

  function installInteractionGate() {
    var blockWhenUnavailable = function (event) {
      if (state.staticVerified && state.engineVerified) return;
      event.preventDefault();
      event.stopImmediatePropagation();
      if (!state.staticVerified) failClosed('source artifact has not been verified');
    };
    ['pointerdown', 'pointermove', 'pointerup', 'pointercancel'].forEach(function (type) {
      state.pad.addEventListener(type, blockWhenUnavailable, true);
    });
  }

  function installBrushPreview() {
    function rebuildUnion() {
      var selected = new Set();
      state.previewPointers.forEach(function (pointer) {
        pointer.pixelIndices.forEach(function (pixelIndex) { selected.add(pixelIndex); });
      });
      state.previewPixelIndices = selected;
    }
    function update(event) {
      if (!state.engineVerified || !state.previewPointers.has(event.pointerId)) return;
      var rect = state.cachedPadRect || state.pad.getBoundingClientRect();
      state.cachedPadRect = rect;
      var target = padToWorld(
        Math.min(Math.max((event.clientX - rect.left) / rect.width, 0), 1),
        Math.min(Math.max((event.clientY - rect.top) / rect.height, 0), 1),
      );
      if (typeof root.padBrushWorld !== 'function') {
        failEngine('brush radius projection is unavailable');
        return;
      }
      var radius = root.padBrushWorld(target);
      var pointer = state.previewPointers.get(event.pointerId);
      var previous = pointer.target;
      pointer.pixelIndices = affectedPixelIndices(
        state.screenGlyphs,
        {
          axisX: state.view.axisX,
          axisY: state.view.axisY,
          panelId: target.panelId,
          targetX: target.targetX,
          targetY: target.targetY,
          prevX: previous && previous.targetX,
          prevY: previous && previous.targetY,
          radius: radius.x,
          radiusY: radius.y,
        },
      );
      pointer.target = target;
    }
    function queueUpdate(event) {
      if (!state.engineVerified || !state.previewPointers.has(event.pointerId)) return;
      state.previewEvents.set(event.pointerId, {
        pointerId: event.pointerId,
        clientX: event.clientX,
        clientY: event.clientY,
      });
      if (state.previewFrame !== null) return;
      state.previewFrame = root.requestAnimationFrame(function () {
        state.previewFrame = null;
        var latest = Array.from(state.previewEvents.values());
        state.previewEvents.clear();
        latest.forEach(update);
        rebuildUnion();
        scheduleDraw(false);
      });
    }
    state.pad.addEventListener('pointerdown', function (event) {
      if (!state.engineVerified || state.previewPointers.has(event.pointerId)) return;
      if (!root.TouchSpatialContactGate ||
          typeof root.TouchSpatialContactGate.begin !== 'function') {
        failEngine('single-contact gate is unavailable');
        return;
      }
      if (!root.TouchSpatialContactGate.begin(event.pointerId)) return;
      state.previewPointers.set(event.pointerId, { target: null, pixelIndices: new Set() });
      queueUpdate(event);
    });
    state.pad.addEventListener('pointermove', queueUpdate);
    ['pointerup', 'pointercancel'].forEach(function (type) {
      state.pad.addEventListener(type, function (event) {
        if (!state.previewPointers.has(event.pointerId)) return;
        state.previewPointers.delete(event.pointerId);
        state.previewEvents.delete(event.pointerId);
        rebuildUnion();
        scheduleDraw(false);
      });
    });
    root.document.addEventListener('spatialcontactclear', clearBrushPreview);
  }

  function load(viewId) {
    if (typeof root.fetch !== 'function') {
      return Promise.reject(new Error('fetch is unavailable; pixel views cannot load'));
    }
    var urls = [ARTIFACT_URL, VIEWS_SOURCE_URL, CAMERAS_SOURCE_URL].concat(RESOLVER_SOURCE_URLS);
    return Promise.all(urls.map(function (url) {
      return root.fetch(url, { cache: 'no-store' });
    })).then(function (responses) {
      responses.forEach(function (response, index) {
        if (!response.ok) throw new Error(urls[index] + ' HTTP ' + response.status);
      });
      return Promise.all([
        responses[0].json(),
        responses[1].text(),
        responses[2].text(),
        responses[3].text(),
        responses[4].text(),
      ]);
    }).then(function (loaded) {
      var artifact = validateArtifact(loaded[0]);
      return Promise.all([
        verifyResolvedFingerprint(artifact),
        sha256(canonicalSource(loaded[1])),
        sha256(canonicalSource(loaded[2])),
        sha256(canonicalSource(loaded[3]) + '\n-- touch resolver boundary --\n' +
          canonicalSource(loaded[4])),
      ]).then(function (fingerprints) {
        // Staleness is self-healing at the source: the save server re-exports
        // the artifact at boot and after every save that touches an input
        // (save-server.js refreshTouchPixelViews). Reaching one of these
        // refusals therefore means that regeneration did not run or failed —
        // the copy names the remedy instead of only the symptom.
        var REGEN_HINT = ' — restart the sim stack (the save server re-exports it at boot)' +
          ' or run: cd simulation && npm run pixel-views:export';
        if (fingerprints[1] !== artifact.source.viewsFingerprint) {
          throw new Error('pixel-view artifact is stale against pixel_map_views.yaml' + REGEN_HINT);
        }
        if (fingerprints[2] !== artifact.source.camerasFingerprint) {
          throw new Error('pixel-view artifact is stale against cameras.yaml' + REGEN_HINT);
        }
        if (fingerprints[3] !== artifact.source.resolverFingerprint) {
          throw new Error('pixel-view artifact is stale against the simulation resolver' + REGEN_HINT);
        }
        state.artifact = artifact;
        selectView(viewId, false);
        state.staticVerified = true;
        installViewControls();
        scheduleDraw(true);
        return artifact;
      });
    }).catch(function (error) {
      failClosed(error.message);
      throw error;
    });
  }

  function startReady(viewId) {
    state.readyStatus = 'pending';
    state.readyPromise = load(viewId).then(function (artifact) {
      state.readyStatus = 'fulfilled';
      return artifact;
    }, function (error) {
      state.readyStatus = 'rejected';
      throw error;
    });
    return state.readyPromise;
  }

  function mount(options) {
    options = options || {};
    state.canvas = options.canvas;
    state.pad = options.pad;
    state.errorElement = options.errorElement;
    state.viewSelect = options.viewSelect || null;
    state.panButton = options.panButton || null;
    state.zoomOutButton = options.zoomOutButton || null;
    state.zoomInButton = options.zoomInButton || null;
    state.zoomValue = options.zoomValue || null;
    state.fitButton = options.fitButton || null;
    if (!state.canvas || !state.pad || !state.errorElement) {
      return Promise.reject(new Error('pixel-view mount needs canvas, pad, and error element'));
    }
    /* Loading is not a failure. Keep input fail-closed while both proofs are
       pending, but do not flash a red operator alarm or emit console errors
       during the normal native boot sequence. */
    markPending();
    installInteractionGate();
    installViewGesture();
    installBrushPreview();
    if (typeof root.ResizeObserver !== 'function') {
      return Promise.reject(new Error('ResizeObserver is unavailable; pixel view cannot reproject'));
    }
    state.resizeObserver = new root.ResizeObserver(function () { scheduleDraw(true); });
    state.resizeObserver.observe(state.canvas);
    return startReady(options.viewId || 'top_down');
  }

  var api = {
    mount: mount,
    ready: function () {
      if (!state.readyPromise) return Promise.reject(new Error('pixel view is not mounted'));
      if (state.readyStatus === 'rejected') {
        return startReady(state.view ? state.view.id : 'top_down');
      }
      return state.readyPromise;
    },
    canArm: function () { return state.staticVerified && state.engineVerified; },
    hasDisplayProjection: function () {
      return state.staticVerified
        && state.screenGlyphs.length > 0
        && state.canvas
        && state.canvas.clientWidth > 0
        && state.canvas.clientHeight > 0;
    },
    refreshDisplayProjection: function () { scheduleDraw(true); },
    verifyEngineLayout: verifyEngineLayout,
    validateArtifact: validateArtifact,
    verifyResolvedFingerprint: verifyResolvedFingerprint,
    topologyPayload: topologyPayload,
    topologyFingerprint: topologyFingerprint,
    reprojectView: reprojectView,
    screenPointToTarget: screenPointToTarget,
    clampZoom: clampZoom,
    zoomAroundPoint: zoomAroundPoint,
    projectionAuthority: root.DeckPixelProjection,
    flattenProjectionView: flattenProjectionView,
    affectedPixelIndices: affectedPixelIndices,
    padPxToWorld: padPxToWorld,
    padToWorld: padToWorld,
    worldToPad: worldToPad,
    padWorldPerPx: padWorldPerPx,
    worldBrushRadii: worldBrushRadii,
    currentViewSpec: currentViewSpec,
    selectView: selectView,
    state: function () {
      return {
        staticVerified: state.staticVerified,
        engineVerified: state.engineVerified,
        readyStatus: state.readyStatus,
        viewId: state.view && state.view.id,
        axisX: state.view && state.view.axisX,
        axisY: state.view && state.view.axisY,
        panMode: state.panMode,
        panX: state.panX,
        panY: state.panY,
        zoom: state.zoom,
        activeNavigationPointers: state.navigationPointers.size,
        staticRenderCount: state.staticRenderCount,
        previewRenderCount: state.previewRenderCount,
        reprojectCount: state.reprojectCount,
        canvasResizeCount: state.canvasResizeCount,
        activePreviewPointers: state.previewPointers.size,
        previewPixelCount: state.previewPixelIndices.size,
        pendingPreviewFrames: state.previewFrame === null ? 0 : 1,
        pendingDrawFrames: state.drawFrame === null ? 0 : 1,
      };
    },
  };

  root.TouchPixelViews = api;
  root.padPxToWorld = padPxToWorld;
  root.padToWorld = padToWorld;
  root.worldToPad = worldToPad;
  root.padWorldPerPx = padWorldPerPx;
  if (typeof module === 'object' && module.exports) module.exports = api;
}(typeof window !== 'undefined' ? window : globalThis));
