#!/usr/bin/env node
// sync-secret.mjs — bake marsin_engine/secret.yaml into the app bundle.
// =====================================================================
//
// PortWatch shares ONE AES-128 pre-shared key with every other component
// in the TITANIC stack (engine, bridge, captain companions). The
// canonical file is `<repo>/marsin_engine/secret.yaml` (gitignored).
//
// Mobile bundles can't read arbitrary files at runtime, so this script
// derives the 16-byte key from that YAML at BUILD time and emits a
// gitignored TypeScript module the app imports as a normal value.
//
// ── Profile-aware behaviour ──────────────────────────────────────────
//
// The build profile (development / preview / production) decides where
// the key comes from and whether we'll fail loudly on a missing one:
//
//   * `development` / `preview` (and `npm run start`/`run ios` locally):
//     the key MUST come from marsin_engine/secret.yaml. We fail fast
//     if the file is missing — running a dev build with a silently
//     stubbed key would let the operator believe the radio is encrypted
//     when it isn't.
//
//   * `production`: no key is baked into the bundle. PortWatch falls
//     back to its in-app key entry sheet (see ScanScreen secret-setup
//     flow), which stores the key in iOS Keychain via
//     expo-secure-store. Dev keys must NEVER ride a TestFlight or App
//     Store binary, even by accident — this is the policy gate.
//
//   * `--allow-missing` (CLI): emits a tripwire stub instead of failing.
//     Used by `postinstall` so `npm install` always succeeds before
//     the user has dropped a secret.yaml in place. The actual build
//     scripts re-run sync-secret WITHOUT --allow-missing.
//
// Profile resolution:
//   1. CLI flag `--profile <name>` (highest precedence)
//   2. `EAS_BUILD_PROFILE` env var (set by EAS during cloud builds)
//   3. `EXPO_PUBLIC_PORTWATCH_PROFILE` env var (set in eas.json)
//   4. `PORTWATCH_PROFILE` env var (manual override for local testing)
//   5. fallback: "development"
//
// Output: `src/_generated/secret.generated.ts`

import { createHash } from "node:crypto";
import { readFileSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));

const APP_ROOT = resolve(__dirname, "..");
const REPO_ROOT = resolve(__dirname, "..", "..", "..");
const SECRET_PATH =
  process.env.TITANIC_SECRET_PATH ||
  resolve(REPO_ROOT, "marsin_engine", "secret.yaml");
const OUT_DIR = resolve(APP_ROOT, "src", "_generated");
const OUT_FILE = resolve(OUT_DIR, "secret.generated.ts");

const KEY_BYTES = 16;

function fail(msg) {
  console.error("\n[sync-secret] " + msg + "\n");
  process.exit(1);
}

// ── Resolve profile ──────────────────────────────────────────────────

function resolveProfile() {
  const argv = process.argv.slice(2);
  const flagIdx = argv.indexOf("--profile");
  if (flagIdx >= 0 && argv[flagIdx + 1]) {
    return argv[flagIdx + 1].toLowerCase();
  }
  return (
    process.env.EAS_BUILD_PROFILE ||
    process.env.EXPO_PUBLIC_PORTWATCH_PROFILE ||
    process.env.PORTWATCH_PROFILE ||
    "development"
  ).toLowerCase();
}

const allowMissing = process.argv.includes("--allow-missing");
const profile = resolveProfile();
const isProductionProfile = profile === "production";

// ── Production: emit a "no key, prompt at runtime" stub ─────────────

function writeProductionStub() {
  // The runtime-entry path. The app sees BAKED_AT_BUILD = false and
  // routes to its key-entry sheet (expo-secure-store backed).
  const stub = [
    "// AUTO-GENERATED by scripts/sync-secret.mjs (production profile).",
    "// No pre-shared key is baked into production builds — PortWatch",
    "// reads the operator-entered key from iOS Keychain at runtime",
    "// (see src/security/secretStore.ts). The 16-byte zero array",
    "// below exists ONLY so the import resolves; the runtime checks",
    "// BAKED_AT_BUILD === false and ignores it.",
    "/* eslint-disable */",
    "export const KEY_BYTES: Uint8Array = new Uint8Array(16);",
    "export const KEY_FINGERPRINT = '<RUNTIME-ENTRY>';",
    "export const KEY_VERSION = 1;",
    "export const KEY_SOURCE_PATH = '<runtime>';",
    "export const BAKED_AT_BUILD = false;",
    "",
  ];
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, stub.join("\n"), "utf8");
  console.log(
    "[sync-secret] production profile: NO key baked. App will prompt at runtime."
  );
}

// ── --allow-missing tripwire stub (postinstall path) ────────────────

function writeAllowMissingStub() {
  const stub = [
    "// AUTO-GENERATED stub by sync-secret.mjs --allow-missing.",
    "// The real secret has NOT been baked in yet. Either:",
    "//   1. Create marsin_engine/secret.yaml (see secret.yaml.example), OR",
    "//   2. Set TITANIC_SECRET_PATH to a different yaml file,",
    "// then run `npm run sync-secret` (or any of the build scripts).",
    "//",
    "// At runtime App.tsx checks for KEY_FINGERPRINT === '<NOT-BAKED>'",
    "// and refuses to scan / connect / send anything.",
    "/* eslint-disable */",
    "export const KEY_BYTES: Uint8Array = new Uint8Array(16);",
    "export const KEY_FINGERPRINT = '<NOT-BAKED>';",
    "export const KEY_VERSION = 0;",
    "export const KEY_SOURCE_PATH = '" + SECRET_PATH.replace(/'/g, "\\'") + "';",
    "export const BAKED_AT_BUILD = false;",
    "",
  ];
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, stub.join("\n"), "utf8");
  console.warn(
    "[sync-secret] WARNING: " +
      SECRET_PATH +
      " not found (postinstall stub).\n" +
      "             The build scripts will re-run sync-secret strictly."
  );
}

// ── Production: never bake a key, always emit the prompt-at-runtime stub.
if (isProductionProfile) {
  writeProductionStub();
  process.exit(0);
}

// ── Dev / preview / unknown profile: must have secret, else stub or fail.
if (!existsSync(SECRET_PATH)) {
  if (allowMissing) {
    writeAllowMissingStub();
    process.exit(0);
  }
  fail(
    `missing secret file: ${SECRET_PATH}\n` +
      `  Bring-up steps:\n` +
      `    cp marsin_engine/secret.yaml.example marsin_engine/secret.yaml\n` +
      `    edit marsin_engine/secret.yaml and set \`key:\` (string) for dev\n` +
      `    or \`key_hex:\` (32 hex chars) for production.\n` +
      `  Profile detected: ${profile}\n` +
      `  Override the path with TITANIC_SECRET_PATH=<file>.`
  );
}

let doc;
try {
  doc = yaml.load(readFileSync(SECRET_PATH, "utf8")) || {};
} catch (err) {
  fail(`${SECRET_PATH}: invalid YAML: ${err.message || err}`);
}
if (typeof doc !== "object" || doc === null) {
  fail(`${SECRET_PATH}: top-level must be a mapping`);
}

const version = doc.version ?? 1;
if (version !== 1) {
  fail(
    `${SECRET_PATH}: unsupported version=${JSON.stringify(version)} ` +
      `(only v1 = AES-128-GCM is implemented)`
  );
}

let keyBytes;
let derivedFrom;

if (typeof doc.key_hex === "string") {
  const hex = doc.key_hex.trim();
  if (!/^[0-9a-fA-F]+$/.test(hex)) {
    fail(`${SECRET_PATH}: key_hex is not valid hex`);
  }
  keyBytes = Buffer.from(hex, "hex");
  if (keyBytes.length !== KEY_BYTES) {
    fail(
      `${SECRET_PATH}: key_hex decodes to ${keyBytes.length} bytes, ` +
        `expected ${KEY_BYTES}`
    );
  }
  derivedFrom = "key_hex (production form)";
} else if (typeof doc.key === "string" && doc.key.length > 0) {
  keyBytes = createHash("sha256").update(doc.key, "utf8").digest().subarray(0, KEY_BYTES);
  derivedFrom = "key (dev form: SHA-256 → 16 bytes)";
} else {
  fail(
    `${SECRET_PATH}: must contain either \`key:\` (string) or ` +
      `\`key_hex:\` (32 hex chars)`
  );
}

mkdirSync(OUT_DIR, { recursive: true });

const bytesLiteral = Array.from(keyBytes)
  .map((b) => "0x" + b.toString(16).padStart(2, "0"))
  .join(", ");

const fingerprint = createHash("sha256").update(keyBytes).digest("hex").slice(0, 16);

const banner = [
  "// AUTO-GENERATED by scripts/sync-secret.mjs — DO NOT EDIT.",
  "// Profile: " + profile,
  "// Source:  " + SECRET_PATH.replace(REPO_ROOT, "<repo>"),
  "// Form:    " + derivedFrom,
  "// Key fingerprint (sha256 of key, first 16 hex chars): " + fingerprint,
  "// This file is gitignored — re-run `npm run sync-secret` to refresh.",
  "//",
  "// The fingerprint lets you sanity-check that every machine in the camp",
  "// is running the same secret without ever exposing the key itself.",
  "",
  "/* eslint-disable */",
  "",
  "export const KEY_BYTES: Uint8Array = new Uint8Array([",
  "  " + bytesLiteral + ",",
  "]);",
  "",
  "export const KEY_FINGERPRINT = " + JSON.stringify(fingerprint) + ";",
  "export const KEY_VERSION = " + JSON.stringify(version) + ";",
  "export const KEY_SOURCE_PATH = " + JSON.stringify(SECRET_PATH) + ";",
  "export const BAKED_AT_BUILD = true;",
  "",
];

writeFileSync(OUT_FILE, banner.join("\n"), "utf8");

console.log(
  "[sync-secret] profile=" +
    profile +
    "  wrote " +
    OUT_FILE.replace(APP_ROOT, ".") +
    "  (fingerprint " +
    fingerprint +
    ", from " +
    derivedFrom +
    ")"
);
