version: 1
views:
  - id: top_down
    label: Top-Down
    panels:
      - id: main
        select:
          - fixtureType: ShehdsBar
          - kind: led
          - group: Left SmokeStack
          - group: Right SmokeStacks
          - group: Left Small SmokeStack
          - group: Right Small SmokeStack
          - group: Left Auditorium
          - group: Right Auditorium
          - group: Left Back Rails
          - group: Right Back Rails
          - group: Left Front Rails
          - group: Right Front Rails
          - group: TE Sign
          - group: TE Sign 2
        layout: spatial
        label: All Fixtures
        projection: top
        expandPitch:
          VintageLed:
            pitch: 0.4
            layout: line
    placements: {}
    typeStyles:
      UkingPar:
        sizeX: 13
        sizeY: 13
      LedStrand:
        sizeX: 5
        sizeY: 5
      ShehdsBar:
        sizeX: 7
        sizeY: 7
      VintageLed:
        sizeX: 6
        sizeY: 6
      TeSignV3A40:
        sizeX: 4
        sizeY: 4
      TeSignV3B34:
        sizeX: 4
        sizeY: 4
    framing:
      zoom: 0.6355180784048313
      panX: -424.333929874922
      panY: -187.6006627809905
  - id: front
    label: Front
    panels:
      - id: left
        select:
          - group: Left Front Wall
          - group: Left Front Rails
          - group: Left_Front_Left
          - group: Left_Front_Right
          - name: Left SmokeStack 1
          - name: Left SmokeStack 2
          - name: Left SmokeStack 3
          - name: Left SmokeStack 4
        layout: spatial
        label: Left Front
        projection: front
        washAngle: -30
        expandPitch:
          VintageLed:
            pitch: 0.4
            layout: line
            direction: vertical
          ShehdsBar:
            pitch: 0.1
            layout: line
      - id: right
        select:
          - group: Right Front Wall
          - group: Right Front Rails
          - group: Right_Front_Right
          - group: Right_Front_Left
          - group: TE Sign 2
          - name: Right SmokeStacks 5
          - name: Right SmokeStacks 6
          - name: Right SmokeStacks 7
          - name: Right SmokeStacks 8
        layout: spatial
        label: Right Front
        projection: front
        washAngle: 33
        expandPitch:
          VintageLed:
            pitch: 0.4
            layout: line
            direction: vertical
          ShehdsBar:
            pitch: 0.1
            layout: line
    placements: {}
    typeStyles:
      VintageLed:
        sizeX: 8
        sizeY: 8
      UkingPar:
        sizeX: 12
        sizeY: 12
      ShehdsBar:
        sizeX: 3
        sizeY: 3
      LedStrand:
        sizeX: 4
        sizeY: 4
      TeSignV3A40:
        sizeX: 3
        sizeY: 3
      TeSignV3B34:
        sizeX: 3
        sizeY: 3
  - id: back
    label: Back
    panels:
      - id: left_back
        select:
          - group: Left Back Wall
          - group: Left Back Rails
          - group: Left_Back_Left
          - group: Left_Back_Right
          - group: Left Auditorium
          - group: Left Small SmokeStack
          - name: Left SmokeStack 5
          - name: Left SmokeStack 6
          - name: Left SmokeStack 7
          - name: Left SmokeStack 8
        layout: spatial
        label: Left Back
        projection: front
        washAngle: -30
        expandPitch:
          VintageLed:
            pitch: 0.4
            layout: line
            direction: vertical
          ShehdsBar:
            pitch: 0.15
            layout: line
      - id: right_back
        select:
          - group: Right Back Wall
          - group: Right Back Rails
          - group: Right_Back_Left
          - group: Right_Back_Right
          - group: Right Auditorium
          - group: Right Small SmokeStack
          - name: Right SmokeStacks 1
          - name: Right SmokeStacks 2
          - name: Right SmokeStacks 3
          - name: Right SmokeStacks 4
        layout: spatial
        label: Right Back
        projection: front
        washAngle: 33
        expandPitch:
          VintageLed:
            pitch: 0.4
            layout: line
            direction: vertical
          ShehdsBar:
            pitch: 0.15
            layout: line
    placements: {}
    typeStyles:
      VintageLed:
        sizeX: 8
        sizeY: 8
      UkingPar:
        sizeX: 12
        sizeY: 12
      ShehdsBar:
        sizeX: 3
        sizeY: 3
      LedStrand:
        sizeX: 4
        sizeY: 4
      TeSignV3A40:
        sizeX: 3
        sizeY: 3
      TeSignV3B34:
        sizeX: 3
        sizeY: 3
    offsets:
      Left Auditorium 1:
        dx: -56
        dy: 0
      Left Auditorium 2:
        dx: -41
        dy: 5
      Left Auditorium 3:
        dx: -25
        dy: 8
      Left Auditorium 4:
        dx: -8
        dy: 18
      Left Auditorium 5:
        dx: 8
        dy: 0
      Left Auditorium 6:
        dx: 24
        dy: 0
      Left Auditorium 7:
        dx: 40
        dy: 0
      Left Auditorium 8:
        dx: 56
        dy: 0
      Left Small SmokeStack 2:
        dx: 0
        dy: -16
      Left Small SmokeStack 4:
        dx: 0
        dy: 16
      Left SmokeStack 5:
        dx: 8
        dy: 0
      Left SmokeStack 7:
        dx: -8
        dy: 2
      Right Auditorium 1:
        dx: 0
        dy: 16
      Right Auditorium 2:
        dx: 0
        dy: 16
      Right Auditorium 4:
        dx: -4
        dy: 16
      Right Small SmokeStack 2:
        dx: 8
        dy: 0
      Right Small SmokeStack 4:
        dx: 20
        dy: 12
      Right SmokeStacks 2:
        dx: 18
        dy: 0
  - id: strands
    label: LED Strands
    panels:
      - id: main
        select:
          - kind: led
        layout: spatial
        exclude:
          - fixtureType: TeSignV3A40
          - fixtureType: TeSignV3B34
        projection: top
        expandPitch:
          LedStrand:
            pitch: 0.4
            layout: line
    placements: {}
    typeStyles:
      LedStrand:
        sizeX: 2
        sizeY: 2
    offsets:
      Left_Front_Right:
        dx: 272
        dy: -112
      Left_Back_Right:
        dx: 272
        dy: -112
      Left_Back_Left:
        dx: 272
        dy: -112
      Left_Front_Left:
        dx: 272
        dy: -112
  - id: te_sign
    label: TE Sign
    panels:
      - id: sign_1
        select:
          - fixtureType: TeSignV3A40
            group: TE Sign
          - fixtureType: TeSignV3B34
            group: TE Sign
        layout: planar
        label: TE Sign
        rotate: 90
        fit: true
      - id: sign_2
        select:
          - fixtureType: TeSignV3A40
            group: TE Sign 2
          - fixtureType: TeSignV3B34
            group: TE Sign 2
        layout: planar
        label: TE Sign 2
        rotate: 90
        fit: true
    placements: {}
    typeStyles: {}
