titanicEnd:
  _section:
    label: 🧊 Icebergs
    type: icebergArray
    collapsed: true
  icebergsEnabled:
    value: false
    label: Master Enabled
  focusOnSelect:
    value: false
    label: Focus on Select
  masterFloodEnabled:
    value: false
    label: Master Flood Enabled
  masterFloodColor:
    value: '#ffffff'
    label: Master Flood Color
    type: color
  masterFloodIntensity:
    value: 0
    label: Master Flood Intensity
    min: 0
    max: 500
    step: 1
  masterFloodAngle:
    value: 51
    label: Master Flood Angle °
    min: 10
    max: 90
    step: 1
  masterFloodDimmer:
    value: 0
    label: Master Flood Dimmer %
    min: 0
    max: 250
    step: 1
  icebergs: []
modelTransform:
  _section:
    label: 📦 Model Transform
    collapsed: true
  modelX:
    value: 0
    label: Pos X
    min: -500
    max: 500
    step: 1
    listen: true
  modelY:
    value: 0
    label: Pos Y
    min: -500
    max: 500
    step: 1
    listen: true
  modelZ:
    value: 0
    label: Pos Z
    min: -500
    max: 500
    step: 1
    listen: true
  rotX:
    value: 0
    label: Rot X °
    min: -180
    max: 180
    step: 1
    listen: true
  rotY:
    value: 0
    label: Rot Y °
    min: -180
    max: 180
    step: 1
    listen: true
  rotZ:
    value: 0
    label: Rot Z °
    min: -180
    max: 180
    step: 1
    listen: true
parLights:
  _section:
    label: 🔌 DMX Fixtures
    type: fixtureArray
    collapsed: false
  parsEnabled:
    value: true
    label: Master Enabled
  masterExposure:
    value: 0.2
    label: Sim Exposure (Preview Only)
    min: 0
    max: 2
    step: 0.05
  simBrightness:
    value: 1
    label: Sim Brightness (Preview Only)
    min: 0
    max: 2
    step: 0.05
  simSurfaceReflectance:
    value: 0.3
    label: Sim Ground Reflectance (Preview Only)
    min: 0.1
    max: 1
    step: 0.05
  maxSpotlights:
    value: 60
    label: Max Spotlights
    min: 1
    max: 200
    step: 1
  conesEnabled:
    value: false
    label: Show Light Cones
  generatorsVisible:
    value: false
    label: Show Generators
  fixtures:
    - group: TriangleEdges
      name: ShehdsBar 54
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: -0.34992128010745205
      'y': 2.5
      z: 5.16815858009418
      rotX: -0.0
      rotY: 0
      rotZ: 0
    - group: TriangleEdges
      name: ShehdsBar 21
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 0.10964267857508764
      'y': 3.527116342444624
      z: 5.219240164031626
      rotX: 0
      rotY: 0
      rotZ: -56.61317144274455
    - group: TriangleEdges
      name: ShehdsBar 22
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: -0.7448054919903544
      'y': 3.535042521895957
      z: 5.190285683104403
      rotX: -0.0
      rotY: 0
      rotZ: 52.50545540754772
    - group: TrianglePars
      name: UkingPar 23
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 20
      angle: 20
      penumbra: 0.5
      x: 1.6835444712338985
      'y': 3.4288811329809743
      z: 6.686670656144868
      rotX: -60.94486375723701
      rotY: 0
      rotZ: 0
    - group: TrianglePars
      name: UkingPar 25
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 20
      angle: 20
      penumbra: 0.5
      x: -2.583081207111756
      'y': 3.6031171228316845
      z: 6.78192102402529
      rotX: -59.645707765494386
      rotY: 0
      rotZ: 0
    - group: TriangleEdges
      name: ShehdsBar 2
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: -0.3364236028168859
      'y': 2.949275770276158
      z: 5.16815858009418
      rotX: -0.0
      rotY: 0
      rotZ: 0
    - group: Fogger
      name: ChauvetHaze4D 24
      fixtureType: ChauvetHaze4D
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 1
      'y': 1
      z: 6
      rotX: 0
      rotY: 0
      rotZ: 0
    - group: BarLights
      name: BarLights 1
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 4.5480679169723315
      'y': 1.5
      z: -8.905901314443529
      rotX: -142.14635354864927
      rotY: -27.05250355696975
      rotZ: 0
      traceGenerated: true
    - group: BarLights
      name: BarLights 2
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 9.513392877409316
      'y': 1.5
      z: -3.081453546633095
      rotX: -142.14635354864927
      rotY: -72.05250355696982
      rotZ: 0
      traceGenerated: true
    - group: BarLights
      name: BarLights 3
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 8.905901314443529
      'y': 1.5
      z: 4.548067916972331
      rotX: -142.14635354864927
      rotY: -117.05250355696977
      rotZ: 0
      traceGenerated: true
    - group: BarLights
      name: BarLights 4
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 3.081453546633095
      'y': 1.5
      z: 9.513392877409316
      rotX: -142.14635354864927
      rotY: -162.0525035569698
      rotZ: 0
      traceGenerated: true
    - group: BarLights
      name: BarLights 5
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -4.548067916972331
      'y': 1.5
      z: 8.905901314443529
      rotX: -142.14635354864927
      rotY: 152.94749644303025
      rotZ: 0
      traceGenerated: true
    - group: BarLights
      name: BarLights 6
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -9.513392877409318
      'y': 1.5
      z: 3.081453546633097
      rotX: -142.14635354864927
      rotY: 107.94749644303022
      rotZ: 0
      traceGenerated: true
    - group: BarLights
      name: BarLights 7
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -8.905901314443529
      'y': 1.5
      z: -4.54806791697233
      rotX: -142.14635354864927
      rotY: 62.947496443030246
      rotZ: 0
      traceGenerated: true
    - group: BarLights
      name: BarLights 8
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -3.0814535466330972
      'y': 1.5
      z: -9.513392877409316
      rotX: -142.14635354864927
      rotY: 17.9474964430302
      rotZ: 0
      traceGenerated: true
    - group: VintageLights
      name: VintageLights 1
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 7.5175409662872665
      'y': 2.5
      z: -2.73616114660535
      rotX: -162.6459753637387
      rotY: -69.99999999999999
      rotZ: 0
      traceGenerated: true
    - group: VintageLights
      name: VintageLights 2
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 7.2504622962931995
      'y': 2.5
      z: 3.380946093925594
      rotX: -162.6459753637387
      rotY: -115.00000000000003
      rotZ: 0
      traceGenerated: true
    - group: VintageLights
      name: VintageLights 3
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 2.7361611466053506
      'y': 2.5
      z: 7.5175409662872665
      rotX: -162.6459753637387
      rotY: -159.99999999999997
      rotZ: 0
      traceGenerated: true
    - group: VintageLights
      name: VintageLights 4
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -3.380946093925594
      'y': 2.5
      z: 7.2504622962931995
      rotX: -162.6459753637387
      rotY: 155.00000000000003
      rotZ: 0
      traceGenerated: true
    - group: VintageLights
      name: VintageLights 5
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -7.5175409662872665
      'y': 2.5
      z: 2.736161146605351
      rotX: -162.6459753637387
      rotY: 110.00000000000007
      rotZ: 0
      traceGenerated: true
    - group: VintageLights
      name: VintageLights 6
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -7.2504622962932
      'y': 2.5
      z: -3.3809460939255938
      rotX: -162.6459753637387
      rotY: 64.99999999999999
      rotZ: 0
      traceGenerated: true
    - group: VintageLights
      name: VintageLights 7
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -2.7361611466053515
      'y': 2.5
      z: -7.517540966287266
      rotX: -162.6459753637387
      rotY: 20
      rotZ: 0
      traceGenerated: true
    - group: VintageLights
      name: VintageLights 8
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 3.380946093925593
      'y': 2.5
      z: -7.2504622962932
      rotX: -162.6459753637387
      rotY: -25.000000000000018
      rotZ: 0
      traceGenerated: true
ledStrands:
  _section:
    label: 💡 LED Strands
    type: ledStrandArray
    collapsed: true
  strandsEnabled:
    value: true
    label: Master Enabled
  strands: []
traces:
  - name: BarLights
    shape: circle
    radius: 10
    arc: 360
    spacing: 8
    x: 0
    'y': 1.5
    z: 0
    rotX: -0.0
    rotY: 62.94749644303021
    rotZ: 0
    aimMode: direction_yz_locked
    aimX: 13.5
    aimY: -1.5
    aimZ: 0
    lightColor: '#ffaa44'
    lightIntensity: 10
    lightAngle: 30
    groupName: BarLights
    fixtureType: ShehdsBar
    generated: true
    controllerIp: ''
    fixtureRotOffX: 0
    fixtureRotOffY: 0
    fixtureRotOffZ: 0
    locked: false
  - name: VintageLights
    shape: circle
    radius: 8
    arc: 360
    spacing: 6
    x: 0
    'y': 2.5
    z: 0
    rotX: -0.0
    rotY: 20.000000000000007
    rotZ: 0
    aimMode: lookAt_yz_locked
    aimX: 0
    aimY: 0
    aimZ: 0
    lightColor: '#ffaa44'
    lightIntensity: 10
    lightAngle: 30
    groupName: VintageLights
    fixtureType: VintageLed
    generated: true
    controllerIp: ''
    fixtureRotOffX: 0
    fixtureRotOffY: 0
    fixtureRotOffZ: 0
    locked: false
