titanicEnd:
  _section:
    label: 🧊 Icebergs
    type: icebergArray
    collapsed: true
  icebergsEnabled:
    value: false
    label: Master Enabled
  focusOnSelect:
    value: false
    label: Focus on Select
  masterFloodEnabled:
    value: false
    label: Master Flood Enabled
  masterFloodColor:
    value: '#ffffff'
    label: Master Flood Color
    type: color
  masterFloodIntensity:
    value: 0
    label: Master Flood Intensity
    min: 0
    max: 500
    step: 1
  masterFloodAngle:
    value: 51
    label: Master Flood Angle °
    min: 10
    max: 90
    step: 1
  masterFloodDimmer:
    value: 0
    label: Master Flood Dimmer %
    min: 0
    max: 250
    step: 1
  icebergs: []
modelTransform:
  _section:
    label: 📦 Model Transform
    collapsed: true
  modelX:
    value: 0
    label: Pos X
    min: -500
    max: 500
    step: 1
    listen: true
  modelY:
    value: 0
    label: Pos Y
    min: -500
    max: 500
    step: 1
    listen: true
  modelZ:
    value: 0
    label: Pos Z
    min: -500
    max: 500
    step: 1
    listen: true
  rotX:
    value: 0
    label: Rot X °
    min: -180
    max: 180
    step: 1
    listen: true
  rotY:
    value: 0
    label: Rot Y °
    min: -180
    max: 180
    step: 1
    listen: true
  rotZ:
    value: 0
    label: Rot Z °
    min: -180
    max: 180
    step: 1
    listen: true
parLights:
  _section:
    label: 🔌 DMX Fixtures
    type: fixtureArray
    collapsed: false
  parsEnabled:
    value: true
    label: Master Enabled
  masterExposure:
    value: 0.2
    label: Sim Exposure (Preview Only)
    min: 0
    max: 2
    step: 0.05
  simBrightness:
    value: 1
    label: Sim Brightness (Preview Only)
    min: 0
    max: 2
    step: 0.05
  simSurfaceReflectance:
    value: 0.3
    label: Sim Ground Reflectance (Preview Only)
    min: 0.1
    max: 1
    step: 0.05
  maxSpotlights:
    value: 60
    label: Max Spotlights
    min: 1
    max: 200
    step: 1
  conesEnabled:
    value: false
    label: Show Light Cones
  generatorsVisible:
    value: false
    label: Show Generators
  fixtures:
    - group: TowerBars
      name: TowerFrontRight
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 6.689501670873074
      'y': 3
      z: 6.5
      rotX: -70
      rotY: 0
      rotZ: 0
    - group: TowerBars
      name: TowerLeftFront
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 8.5
      'y': 3
      z: 8.309875232585572
      rotX: -80.00000000000017
      rotY: -90.00000000000016
      rotZ: -3.663216883927333e-14
    - group: TowerBars
      name: TowerRightBack
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 5
      'y': 3
      z: 8.040498854381248
      rotX: -80.00000000000014
      rotY: 90.0000000000006
      rotZ: -4.0295385723200765e-13
    - group: TowerVintageLights
      name: TowerFrontRightVintage
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 5.049758203708605
      'y': 3.0678628544504076
      z: 6.669003175692958
      rotX: -55.00000000000003
      rotY: 41.505273128087616
      rotZ: 5.545127867695253e-15
    - group: TowerVintageLights
      name: TowerFrontLeftVintage
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 8.397241466138407
      'y': 3.0678628544504076
      z: 6.669003175692958
      rotX: -55.000000000000014
      rotY: -51.82815281392246
      rotZ: 5.545127867695253e-15
    - group: TowerVintageLights
      name: TowerBackRightVintage
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 5
      'y': 3
      z: 10
      rotX: -59.99999999999999
      rotY: 138.7300186117625
      rotZ: 0
    - group: TowerVintageLights
      name: TowerBackLeftVintage
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 8.410504076299194
      'y': 3.0678628544504076
      z: 9.948598948898022
      rotX: -60.00000000000005
      rotY: -132.01857479625406
      rotZ: 1.2722218725854084e-14
    - group: DJ Lights
      name: DJLightLeft
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 7.422965986131673
      'y': 1.5
      z: 6.450692644851269
      rotX: -0.0
      rotY: 0
      rotZ: 0
    - group: DJ Lights
      name: DJLightRight
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 5
      angle: 20
      penumbra: 0.5
      x: 5.108211940012689
      'y': 1.5
      z: 6.250381843892892
      rotX: -0.0
      rotY: 0
      rotZ: 0
    - group: WallVintageLights
      name: WallVintageLights 1
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -5
      'y': 2
      z: 0
      rotX: 0
      rotY: 354.28940686250036
      rotZ: 0
      traceGenerated: true
    - group: WallVintageLights
      name: WallVintageLights 2
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -0.1999999999999993
      'y': 2
      z: 0
      rotX: 0
      rotY: 354.28940686250036
      rotZ: 0
      traceGenerated: true
    - group: WallVintageLights
      name: WallVintageLights 3
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 4.600000000000001
      'y': 2
      z: 0
      rotX: 0
      rotY: 354.28940686250036
      rotZ: 0
      traceGenerated: true
    - group: WallVintageLights
      name: WallVintageLights 4
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 9.399999999999999
      'y': 2
      z: 0
      rotX: 0
      rotY: 354.28940686250036
      rotZ: 0
      traceGenerated: true
    - group: WallVintageLights
      name: WallVintageLights 5
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 14.200000000000003
      'y': 2
      z: 0
      rotX: 0
      rotY: 354.28940686250036
      rotZ: 0
      traceGenerated: true
    - group: WallVintageLights
      name: WallVintageLights 6
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 19
      'y': 2
      z: 0
      rotX: 0
      rotY: 354.28940686250036
      rotZ: 0
      traceGenerated: true
    - group: Redwoods1
      name: Redwoods1 1
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 9
      'y': 3
      z: 21
      rotX: -39.80557109226518
      rotY: 89.99999999999997
      rotZ: -39.805571092265176
      traceGenerated: true
    - group: Redwoods1
      name: Redwoods1 2
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 7.5
      'y': 3
      z: 23.598076211353316
      rotX: -39.805571092265176
      rotY: 29.999999999999993
      rotZ: -11.081962544938204
      traceGenerated: true
    - group: Redwoods1
      name: Redwoods1 3
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 4.500000000000001
      'y': 3
      z: 23.598076211353316
      rotX: -39.8055710922652
      rotY: -29.999999999999986
      rotZ: 11.081962544938204
      traceGenerated: true
    - group: Redwoods1
      name: Redwoods1 4
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 3
      'y': 3
      z: 21
      rotX: -39.80557109226518
      rotY: -89.99999999999997
      rotZ: 39.805571092265176
      traceGenerated: true
    - group: Redwoods1
      name: Redwoods1 5
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 4.499999999999998
      'y': 3
      z: 18.401923788646684
      rotX: -39.80557109226518
      rotY: -149.99999999999997
      rotZ: 106.99052439091469
      traceGenerated: true
    - group: Redwoods1
      name: Redwoods1 6
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 7.5
      'y': 3
      z: 18.401923788646684
      rotX: -39.80557109226518
      rotY: 149.99999999999997
      rotZ: -106.99052439091474
      traceGenerated: true
    - group: Redwoods2
      name: Redwoods2 1
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 29.80472889280884
      'y': 3
      z: -17.434008125051907
      rotX: -43.6354553514565
      rotY: 76.574337235283
      rotZ: -35.074777167064106
      traceGenerated: true
    - group: Redwoods2
      name: Redwoods2 2
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 26.80472889280884
      'y': 3
      z: -14.434008125051907
      rotX: -38.801601538031846
      rotY: 0.9279470872123877
      rotZ: -0.3268025891659251
      traceGenerated: true
    - group: Redwoods2
      name: Redwoods2 3
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 23.80472889280884
      'y': 3
      z: -17.434008125051907
      rotX: -44.72446641329507
      rotY: -76.04357158354665
      rotZ: 35.66309740064611
      traceGenerated: true
    - group: Redwoods2
      name: Redwoods2 4
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 26.80472889280884
      'y': 3
      z: -20.434008125051907
      rotX: -52.88326823835898
      rotY: 178.47486186445084
      rotZ: -176.9337775378601
      traceGenerated: true
    - group: Redwoods3
      name: Redwoods3 1
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 23
      'y': 2.5
      z: 21
      rotX: -45.00000000000001
      rotY: 90
      rotZ: -45
      traceGenerated: true
    - group: Redwoods3
      name: Redwoods3 2
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 21.5
      'y': 2.5
      z: 23.598076211353316
      rotX: -41.92468008602947
      rotY: 21.05172443537292
      rotZ: -8.14336553121091
      traceGenerated: true
    - group: Redwoods3
      name: Redwoods3 3
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 18.5
      'y': 2.5
      z: 23.598076211353316
      rotX: -37.325261491495944
      rotY: -37.58908946897495
      rotZ: 13.114188560391758
      traceGenerated: true
    - group: Redwoods3
      name: Redwoods3 4
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 17
      'y': 2.5
      z: 21
      rotX: -35.537677791974374
      rotY: -90
      rotZ: 35.53767779197438
      traceGenerated: true
    - group: Redwoods3
      name: Redwoods3 5
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 18.5
      'y': 2.5
      z: 18.401923788646684
      rotX: -37.32526149149593
      rotY: -142.41091053102505
      rotZ: 89.56619493142807
      traceGenerated: true
    - group: Redwoods3
      name: Redwoods3 6
      fixtureType: UkingPar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 21.5
      'y': 2.5
      z: 18.401923788646684
      rotX: -41.92468008602948
      rotY: 158.9482755646271
      rotZ: -128.25381549608548
      traceGenerated: true
    - group: WallVintageLightsTop
      name: WallVintageLightsTop 1
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 8.099713113318899
      'y': 5
      z: 0
      rotX: -35.72021350847793
      rotY: 0
      rotZ: 0
      traceGenerated: true
    - group: WallVintageLightsTop
      name: WallVintageLightsTop 2
      fixtureType: VintageLed
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 16.32906321924115
      'y': 5
      z: 0
      rotX: -35.72021350847793
      rotY: 0
      rotZ: 0
      traceGenerated: true
    - group: LedBarsWall
      name: LedBarsWall 1
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: -3
      'y': 0.5
      z: 0
      rotX: -9.607757082724717
      rotY: -0.24868885525858486
      rotZ: 1.489700686984738
      traceGenerated: true
    - group: LedBarsWall
      name: LedBarsWall 2
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 3.5
      'y': 0.6666666666666666
      z: 0
      rotX: -9.607757082724715
      rotY: -0.2486888552585848
      rotZ: 1.489700686984738
      traceGenerated: true
    - group: LedBarsWall
      name: LedBarsWall 3
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 10
      'y': 0.8333333333333333
      z: 0
      rotX: -9.607757082724717
      rotY: -0.24868885525858486
      rotZ: 1.489700686984738
      traceGenerated: true
    - group: LedBarsWall
      name: LedBarsWall 4
      fixtureType: ShehdsBar
      color: '#ffaa44'
      intensity: 10
      angle: 30
      penumbra: 0.5
      x: 16.5
      'y': 1
      z: 0
      rotX: -9.607757082724717
      rotY: -0.24868885525858486
      rotZ: 1.489700686984738
      traceGenerated: true
    - group: Fogger
      name: TEFogMachine 39
      fixtureType: TEFogMachine
      color: '#ffaa44'
      intensity: 0
      angle: 20
      penumbra: 0.5
      x: 0
      'y': 1.5
      z: 0
      rotX: 0
      rotY: 0
      rotZ: 0
ledStrands:
  _section:
    label: 💡 LED Strands
    type: ledStrandArray
    collapsed: true
  strandsEnabled:
    value: true
    label: Master Enabled
  strands: []
traces:
  - name: WallVintageLights
    shape: line
    startX: -5
    startY: 2
    startZ: 0
    endX: 19
    endY: 2
    endZ: 0
    spacing: 4
    aimMode: lookAt_xz_locked
    aimX: -4.5
    aimY: 2
    aimZ: -5
    lightColor: '#ffaa44'
    lightIntensity: 10
    lightAngle: 30
    groupName: WallVintageLights
    fixtureType: VintageLed
    generated: true
    controllerIp: ''
    fixtureRotOffX: 0
    fixtureRotOffY: 0
    fixtureRotOffZ: 0
    locked: false
  - name: Redwoods1
    shape: circle
    radius: 3
    arc: 360
    spacing: 3
    x: 6
    'y': 3
    z: 21
    rotX: -0.0
    rotY: 0
    rotZ: 0
    aimMode: lookAt
    aimX: 6
    aimY: 0.5
    aimZ: 21
    lightColor: '#ffaa44'
    lightIntensity: 10
    lightAngle: 30
    groupName: Redwoods1
    fixtureType: UkingPar
    generated: true
    controllerIp: ''
    fixtureRotOffX: 0
    fixtureRotOffY: 0
    fixtureRotOffZ: 0
    locked: false
  - name: Redwoods2
    shape: circle
    radius: 3
    arc: 360
    spacing: 5
    x: 26.80472889280884
    'y': 3
    z: -17.434008125051907
    rotX: -0.0
    rotY: 0
    rotZ: 0
    aimMode: lookAt
    aimX: 26.74430470921199
    aimY: 0
    aimZ: -18.164552724416478
    lightColor: '#ffaa44'
    lightIntensity: 10
    lightAngle: 30
    groupName: Redwoods2
    fixtureType: UkingPar
    generated: true
    controllerIp: ''
    fixtureRotOffX: 0
    fixtureRotOffY: 0
    fixtureRotOffZ: 0
    locked: false
  - name: Redwoods3
    shape: circle
    radius: 3
    arc: 360
    spacing: 3
    x: 20
    'y': 2.5
    z: 21
    rotX: -0.0
    rotY: 0
    rotZ: 0
    aimMode: lookAt
    aimX: 20.5
    aimY: 0
    aimZ: 21
    lightColor: '#ffaa44'
    lightIntensity: 10
    lightAngle: 30
    groupName: Redwoods3
    fixtureType: UkingPar
    generated: true
    controllerIp: ''
    fixtureRotOffX: 0
    fixtureRotOffY: 0
    fixtureRotOffZ: 0
    locked: false
  - name: WallVintageLightsTop
    shape: line
    startX: 8.099713113318899
    startY: 5
    startZ: 0
    endX: 16.32906321924115
    endY: 5
    endZ: 0
    spacing: 3.5
    aimMode: direction
    aimX: 8.04234123202508
    aimY: 3.324925916781887
    aimZ: -2.329377665239148
    lightColor: '#ffaa44'
    lightIntensity: 10
    lightAngle: 30
    groupName: WallVintageLightsTop
    fixtureType: VintageLed
    generated: true
    controllerIp: ''
    fixtureRotOffX: 0
    fixtureRotOffY: 0
    fixtureRotOffZ: 0
    locked: false
  - name: LedBarsWall
    shape: line
    startX: -3
    startY: 0.5
    startZ: 0
    endX: 16.5
    endY: 1
    endZ: 0
    spacing: 5
    aimMode: direction
    aimX: -2.609716964471062
    aimY: -0.20344403169297243
    aimZ: -4.211898175863379
    lightColor: '#ffaa44'
    lightIntensity: 10
    lightAngle: 30
    groupName: LedBarsWall
    fixtureType: ShehdsBar
    generated: true
    controllerIp: ''
    fixtureRotOffX: 0
    fixtureRotOffY: 0
    fixtureRotOffZ: 0
    locked: false
