"""
Config Store — Load/save the three-file config system.

Files:
  .config.yaml          — Static config (committed): node roles,
                           radio parameters, serial settings, protocol.
  .config.pairing.yaml  — Hardware pairing (gitignored): USB MAC → role,
                           optional BLE address.
  .config.deploy.yaml   — Deploy state (gitignored): timestamps, ports,
                           per-node runtime data, app settings.

load() merges all three into a single dict.
save_pairing() writes only the pairing file.
save_deploy() writes only the deploy file.
"""

from pathlib import Path
from datetime import datetime, timezone
import yaml

BASE = Path(__file__).parent.parent
CONFIG_PATH  = BASE / ".config.yaml"
PAIRING_PATH = BASE / ".config.pairing.yaml"
DEPLOY_PATH  = BASE / ".config.deploy.yaml"


def load():
    """Load and merge static config + pairing + deploy state.

    Returns a single dict with all data merged. Missing pairing or
    deploy files are tolerated (those fields will be None).

    Backward compat: if pairing has 'mac' but no 'usb_mac', treat
    'mac' as 'usb_mac' for seamless migration.
    """
    if not CONFIG_PATH.exists():
        raise FileNotFoundError(f"Static config not found: {CONFIG_PATH}")

    with open(CONFIG_PATH, "r") as f:
        config = yaml.safe_load(f) or {}

    # Load pairing (USB MAC → role, optional BLE address)
    pairing = {}
    if PAIRING_PATH.exists():
        with open(PAIRING_PATH, "r") as f:
            pairing = yaml.safe_load(f) or {}

    # Load deploy state
    deploy = {}
    if DEPLOY_PATH.exists():
        with open(DEPLOY_PATH, "r") as f:
            deploy = yaml.safe_load(f) or {}

    # Merge pairing data into config nodes
    for name, node_cfg in config.get("nodes", {}).items():
        pairing_node = pairing.get("nodes", {}).get(name, {})

        # Backward compat: prefer usb_mac, fall back to legacy mac
        usb_mac = pairing_node.get("usb_mac") or pairing_node.get("mac")
        node_cfg["usb_mac"] = usb_mac
        node_cfg["mac"] = usb_mac  # Keep legacy alias for existing callers
        node_cfg["ble_address"] = pairing_node.get("ble_address")

    # Merge deploy data
    deployed_nodes = deploy.get("deployed_nodes", {})
    # Backward compat: old format used deployed_ports
    deployed_ports = deploy.get("deployed_ports", {})

    for name, node_cfg in config.get("nodes", {}).items():
        dn = deployed_nodes.get(name, {})
        # If rich deploy data exists, use it; else fall back to old ports
        node_cfg["usb_port"] = dn.get("usb_port") or deployed_ports.get(name)
        node_cfg["ble_name"] = dn.get("ble_name")
        node_cfg["ble_address_last_seen"] = dn.get("ble_address_last_seen")
        node_cfg["last_status"] = dn.get("last_status", "unknown")

    config["last_deploy"] = deploy.get("last_deploy")
    config["firmware_version"] = deploy.get("firmware_version")
    config["app"] = deploy.get("app", {})
    config["_pairing_exists"] = PAIRING_PATH.exists()
    config["_deploy_exists"] = DEPLOY_PATH.exists()

    return config


def save_pairing(pairing_nodes):
    """Write pairing file — USB MAC + optional BLE address per node.

    Args:
        pairing_nodes: dict like:
            {"podium": {"usb_mac": "XX:XX:..."}, "server": {"usb_mac": "...", "ble_address": "..."}}

    Also accepts legacy format: {"podium": {"mac": "XX:XX:..."}}
    """
    # Normalize: if caller used legacy 'mac' key, map to 'usb_mac'
    normalized = {}
    for name, data in pairing_nodes.items():
        entry = {}
        entry["usb_mac"] = data.get("usb_mac") or data.get("mac")
        entry["ble_address"] = data.get("ble_address")
        normalized[name] = entry

    data = {"nodes": normalized}
    with open(PAIRING_PATH, "w") as f:
        f.write("# TITANIC Control Podium — Hardware Pairing (GITIGNORED)\n")
        f.write("# Generated by:  python config.py pair\n\n")
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def save_deploy(config, ports=None, deployed_nodes=None, app_settings=None):
    """Write deploy state — rich per-node runtime data.

    Args:
        config: merged config dict (for firmware_version)
        ports: optional legacy dict like {"podium": "COM13"} (backward compat)
        deployed_nodes: optional rich dict like:
            {"podium": {"usb_port": "COM13", "ble_name": "Titanic-Podium", ...}}
        app_settings: optional dict like {"launch_monitor_after_deploy": True}
    """
    # Build deployed_nodes from either rich data or legacy ports
    nodes = {}
    if deployed_nodes:
        nodes = deployed_nodes
    elif ports:
        for name, port in ports.items():
            nodes[name] = {
                "usb_port": port,
                "ble_name": f"Titanic-{name.capitalize()}",
                "ble_address_last_seen": None,
                "last_status": "deployed",
            }

    deploy = {
        "last_deploy": datetime.now(timezone.utc).isoformat(),
        "firmware_version": config.get("firmware_version", "1.0"),
        "deployed_nodes": nodes,
    }

    if app_settings:
        deploy["app"] = app_settings

    with open(DEPLOY_PATH, "w") as f:
        f.write("# TITANIC Control Podium — Deploy State (GITIGNORED)\n")
        f.write("# Generated by:  python deploy.py\n\n")
        yaml.dump(deploy, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


# ── Convenience ──────────────────────────────────────────

def get_node(config, name):
    """Get a node entry by name (e.g. 'podium' or 'server')."""
    return config.get("nodes", {}).get(name)


def node_names(config):
    """Return list of configured node names."""
    return list(config.get("nodes", {}).keys())
