patches:
  Par 1:
    controllerIp: ''
    dmxUniverse: 1
    dmxAddress: 1
    controllerId: 1
    sectionId: 1
    fixtureId: 1
    viewMask: 0
  Par 2:
    controllerIp: ''
    dmxUniverse: 1
    dmxAddress: 11
    controllerId: 1
    sectionId: 1
    fixtureId: 2
    viewMask: 0
  Par 3:
    controllerIp: ''
    dmxUniverse: 1
    dmxAddress: 21
    controllerId: 1
    sectionId: 1
    fixtureId: 3
    viewMask: 0
  VintageLed 1:
    controllerIp: ''
    dmxUniverse: 1
    dmxAddress: 31
    controllerId: 2
    sectionId: 3
    fixtureId: 7
    viewMask: 0
  VintageLed 2:
    controllerIp: ''
    dmxUniverse: 1
    dmxAddress: 64
    controllerId: 2
    sectionId: 3
    fixtureId: 8
    viewMask: 0
  Par 4:
    controllerIp: ''
    dmxUniverse: 1
    dmxAddress: 97
    controllerId: 1
    sectionId: 1
    fixtureId: 4
    viewMask: 0
  Bar Left:
    controllerIp: ''
    dmxUniverse: 1
    dmxAddress: 107
    controllerId: 1
    sectionId: 2
    fixtureId: 5
    viewMask: 0
  Bar Right:
    controllerIp: ''
    dmxUniverse: 1
    dmxAddress: 226
    controllerId: 1
    sectionId: 2
    fixtureId: 6
    viewMask: 0
