version: 1
views:
  - id: top_down
    label: Top-Down
    panels:
      - id: main
        label: Bars + Strands + Stacks + Auditoriums
        select:
          - fixtureType: ShehdsBar
          - kind: led
          - group: Left SmokeStack
          - group: Right SmokeStacks
          - group: Left Small SmokeStack
          - group: Right Small SmokeStack
          - group: Left Auditorium
          - group: Right Auditorium
        exclude:
          - fixtureType: TeSignV3A40
          - fixtureType: TeSignV3B34
        projection: top
        layout: spatial
    placements: {}
    typeStyles:
      UkingPar:
        sizeX: 13
        sizeY: 13
      LedStrand:
        sizeX: 5
        sizeY: 5
      ShehdsBar:
        sizeX: 14
        sizeY: 14

  - id: front
    label: Front
    panels:
      - id: left
        label: Left Front
        select:
          - group: Left Front Wall
          - group: Left Front Rails
          - group: Left_Front_Left
          - group: Left_Front_Right
          - name: Left SmokeStack 1
          - name: Left SmokeStack 2
          - name: Left SmokeStack 3
          - name: Left SmokeStack 4
        projection: front
        layout: spatial
        washAngle: -30
        expandPitch:
          VintageLed: 0.6
      - id: right
        label: Right Front
        select:
          - group: Right Front Wall
          - group: Right Front Rails
          - group: Right_Front_Right
          - group: Right_Front_Left
          - name: Right SmokeStacks 5
          - name: Right SmokeStacks 6
          - name: Right SmokeStacks 7
          - name: Right SmokeStacks 8
        projection: front
        layout: spatial
        washAngle: 33
        expandPitch:
          VintageLed: 0.6
    placements: {}
    typeStyles:
      VintageLed:
        sizeX: 16
        sizeY: 16
      UkingPar:
        sizeX: 18
        sizeY: 60
        effect: upwash

  - id: strands
    label: LED Strands
    panels:
      - id: main
        select:
          - kind: led
        exclude:
          - fixtureType: TeSignV3A40
          - fixtureType: TeSignV3B34
        projection: top
        layout: spatial
    placements: {}
    typeStyles: {}

  - id: te_sign
    label: TE Sign
    panels:
      - id: sign_1
        label: TE Sign
        select:
          - fixtureType: TeSignV3A40
            group: TE Sign
          - fixtureType: TeSignV3B34
            group: TE Sign
        layout: planar
        rotate: 90
        fit: true
      - id: sign_2
        label: TE Sign 2
        select:
          - fixtureType: TeSignV3A40
            group: TE Sign 2
          - fixtureType: TeSignV3B34
            group: TE Sign 2
        layout: planar
        rotate: 90
        fit: true
    placements: {}
    typeStyles: {}
