views:
  groupBits:
    Right Front Wall Generator: 1
    Right Top Chimney Generator: 2
    Right Front Deck Generator: 4
    Right Center Auditorium Generator: 8
    Left Back Wall Generator: 16
    Right Back Wall Generator: 32
    Left Front Wall Generator: 64
    Left Top Chimney Generator: 128
    Left Front Deck Generator: 256
    Left Center Auditorium Generator: 512
    Left_Front_Left: 1024
    Left_Back_Left: 2048
    Left_Back_Right: 4096
    Left_Front_Right: 8192
    Right_Back_Left: 16384
    Right_Back_Right: 32768
    Right_Front_Right: 65536
    Right_Front_Left: 131072
    Right Back Deck Generator: 67108864
    Left Back Deck Generator: 134217728
    Left Center Auditorium: 262144
    Left Back Wall: 524288
    TE Sign: 1048576
  custom: []
